import { describe, expect, test } from 'bun:test';
import { parseKnownEntry } from './schemas';
import { extractSessionSummary } from './summary';
import type { KnownEntry } from './schemas';

const user = (uuid: string, content: unknown): KnownEntry =>
  parseKnownEntry({ type: 'user', uuid, parentUuid: null, timestamp: 't', message: { role: 'user', content } })!;
const summary = (text: string, leafUuid?: string): KnownEntry =>
  parseKnownEntry({ type: 'summary', summary: text, leafUuid })!;

describe('extractSessionSummary', () => {
  test('prefers the first summary whose leafUuid is an entry of this session', () => {
    const entries = [summary('stale summary', 'elsewhere'), summary('real summary', 'u1'), user('u1', 'hello')];
    expect(extractSessionSummary(entries)).toBe('real summary');
  });

  test('falls back to the first user prompt when every summary is plumbing', () => {
    const entries = [summary('<system-reminder>x</system-reminder>', 'u1'), user('u1', 'fix the build')];
    expect(extractSessionSummary(entries)).toBe('fix the build');
  });

  test('skips slash-command plumbing and system reminders in user entries', () => {
    const entries = [
      user('u1', '<command-name>/x</command-name>'),
      user('u2', 'Caveat: The messages below were generated by the user while running local commands.'),
      user('u3', [
        { type: 'text', text: '<system-reminder>context</system-reminder>' },
        { type: 'text', text: 'the real prompt\nsecond line' },
      ]),
    ];
    expect(extractSessionSummary(entries)).toBe('the real prompt');
  });

  test('truncates a long first line to 100 characters', () => {
    const line = 'x'.repeat(120);
    expect(extractSessionSummary([user('u1', line)])).toBe(`${'x'.repeat(97)}...`);
  });
});
