//! Managed-mode supervision of the `CLIProxyAPI` child process.
//!
//! Ownership rules (from the reviewed plan): the child port must be FREE
//! before spawning unless a persisted, identity-verified orphan from this
//! supervisor is still alive; readiness is an authenticated
//! application-level probe, never a bare TCP accept; the exact child PID,
//! start identity, executable, and process group are tracked and killed on
//! shutdown; restarts back off exponentially with a cap and reset after a
//! healthy stretch. Unknown or ambiguous listeners are never adopted or
//! killed.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use anyhow::Context;
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::watch;

use crate::config::UpstreamConfig;
use crate::state::{
    Dirs, create_private_dir, import_legacy_auth, load_or_create_secret, write_private_atomic,
};

const SHUTDOWN_GRACE: Duration = Duration::from_secs(5);
const CHILD_IDENTITY_TIMEOUT: Duration = Duration::from_secs(1);
const REAPER_PORT_TIMEOUT: Duration = Duration::from_secs(2);

#[derive(Debug, Deserialize, Serialize)]
struct ChildRecord {
    format_version: u8,
    pid: i32,
    pgid: i32,
    executable: PathBuf,
    /// Platform-native process start identity: `/proc/<pid>/stat` clock ticks
    /// on Linux, and microseconds since the epoch on macOS. `None` marks the
    /// minimal record written immediately after spawn.
    start_time: Option<u64>,
}

#[derive(Debug, Eq, PartialEq)]
struct ProcessIdentity {
    executable: PathBuf,
    start_time: u64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ChildRecordStatus {
    Verified,
    Dead,
}

/// Timing knobs, overridable in tests.
#[derive(Clone, Debug)]
pub struct Tuning {
    pub readiness_timeout: Duration,
    pub readiness_poll: Duration,
    pub backoff_initial: Duration,
    pub backoff_max: Duration,
    /// Uptime after which the backoff resets (the child was genuinely healthy).
    pub backoff_reset_uptime: Duration,
}

impl Default for Tuning {
    fn default() -> Self {
        Self {
            readiness_timeout: Duration::from_secs(20),
            readiness_poll: Duration::from_millis(250),
            backoff_initial: Duration::from_secs(1),
            backoff_max: Duration::from_secs(30),
            backoff_reset_uptime: Duration::from_mins(1),
        }
    }
}

/// What the request path needs from managed mode.
#[derive(Clone)]
pub struct ManagedHandle {
    pub base_url: String,
    pub credential: crate::headers::GptUpstreamCredential,
    ready: watch::Receiver<bool>,
}

impl ManagedHandle {
    #[must_use]
    pub fn is_ready(&self) -> bool {
        *self.ready.borrow()
    }
}

/// Owns the supervision task; dropping does NOT kill the child — call
/// [`Supervisor::shutdown`] from the serve teardown path.
pub struct Supervisor {
    handle: ManagedHandle,
    shutdown_tx: watch::Sender<bool>,
    task: tokio::task::JoinHandle<()>,
    /// Live child's process group, shared with the supervision task so
    /// [`Supervisor::shutdown`] can force-kill it if the task does not stop
    /// in time (the pgid cannot be recycled while the child is unreaped).
    child_pgid: SharedPgid,
    child_record_file: PathBuf,
}

type SharedPgid = std::sync::Arc<std::sync::Mutex<Option<i32>>>;

/// Double-quoted YAML scalar encoding for EVERY string interpolated into the
/// generated config. Emits only `\"`, `\\`, and `\uXXXX` escapes — all valid
/// in YAML double-quoted style — and escapes DEL/C1 (which YAML's printable
/// set excludes and go-yaml refuses to scan) in addition to C0. Safety lives
/// here, not in per-field validation.
#[must_use]
pub fn yaml_quote(value: &str) -> String {
    use std::fmt::Write as _;
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{00}'..='\u{1f}' | '\u{7f}'..='\u{9f}' => {
                let _ = write!(out, "\\u{:04x}", character as u32);
            }
            _ => out.push(character),
        }
    }
    out.push('"');
    out
}

/// Renders the `CLIProxyAPI` YAML config the router owns in managed mode.
/// Mirrors the config validated in live experiments: loopback bind, dedicated
/// auth dir, single local api key, cloak/control-panel/telemetry disabled.
/// Keyless providers are omitted (doctor and `verify-providers` flag them).
#[must_use]
#[allow(clippy::missing_panics_doc)] // expect() is on a filtered-to-Some iterator
pub fn upstream_config_yaml(
    port: u16,
    auth_dir: &std::path::Path,
    secret: &str,
    providers: &[crate::config::OpenAiProvider],
) -> String {
    use std::fmt::Write as _;
    let mut yaml = format!(
        r"# Generated by model-router; edits are overwritten on every managed start.
host: {host}
port: {port}

auth-dir: {auth_dir}

api-keys:
  - {secret}

remote-management:
  allow-remote: false
  secret-key: {empty}
  disable-control-panel: true

debug: false
logging-to-file: false
usage-statistics-enabled: false

disable-claude-cloak-mode: true

routing:
  strategy: {strategy}
  session-affinity: false
",
        host = yaml_quote("127.0.0.1"),
        auth_dir = yaml_quote(&auth_dir.display().to_string()),
        secret = yaml_quote(secret),
        empty = yaml_quote(""),
        strategy = yaml_quote("round-robin"),
    );
    let mut keyed = providers
        .iter()
        .filter(|provider| provider.api_key.is_some());
    if keyed.clone().next().is_some() {
        yaml.push_str("\nopenai-compatibility:\n");
        for provider in keyed.by_ref() {
            let api_key = provider.api_key.as_deref().expect("filtered to Some");
            let _ = writeln!(yaml, "  - name: {}", yaml_quote(&provider.name));
            let _ = writeln!(yaml, "    base-url: {}", yaml_quote(&provider.base_url));
            yaml.push_str("    api-key-entries:\n");
            let _ = writeln!(yaml, "      - api-key: {}", yaml_quote(api_key));
            yaml.push_str("    models:\n");
            for model in &provider.models {
                let _ = writeln!(yaml, "      - name: {}", yaml_quote(&model.name));
                let alias = crate::config::derived_alias(&model.routing_id);
                let _ = writeln!(yaml, "        alias: {}", yaml_quote(&alias));
            }
        }
    }
    yaml
}

/// Prepares managed-mode state on disk and returns the paths involved.
/// Idempotent; shared by `serve`, `login`, and `doctor`.
///
/// # Errors
/// Returns an error when directories, the secret, or the config cannot be
/// created.
pub fn prepare_managed_state(
    dirs: &Dirs,
    upstream: &UpstreamConfig,
    providers: &[crate::config::OpenAiProvider],
) -> anyhow::Result<ManagedPaths> {
    create_private_dir(&dirs.state_dir)?;
    create_private_dir(&dirs.auth_dir())?;
    create_private_dir(&dirs.log_dir())?;
    let secret = load_or_create_secret(dirs)?;
    import_legacy_auth(dirs)?;
    let yaml = upstream_config_yaml(upstream.port, &dirs.auth_dir(), &secret, providers);
    write_private_atomic(&dirs.upstream_config_file(), yaml.as_bytes())?;
    Ok(ManagedPaths {
        upstream_config: dirs.upstream_config_file(),
        auth_dir: dirs.auth_dir(),
        log_file: dirs.log_dir().join("cliproxyapi.log"),
        secret,
        port: upstream.port,
    })
}

pub struct ManagedPaths {
    pub upstream_config: PathBuf,
    pub auth_dir: PathBuf,
    pub log_file: PathBuf,
    pub secret: String,
    pub port: u16,
}

impl Supervisor {
    /// Starts the supervision loop. Only cheap local state (secret,
    /// directories) is prepared up front; acquisition, the port-free check,
    /// spawning, and readiness all run — and retry with backoff — INSIDE the
    /// loop, so a failing cliproxy upstream never takes down the Claude gateway.
    ///
    /// # Errors
    /// Returns an error only when local state (directories, the create-once
    /// secret) cannot be prepared.
    pub fn start(
        dirs: &Dirs,
        upstream: &UpstreamConfig,
        providers: Vec<crate::config::OpenAiProvider>,
        tuning: Tuning,
    ) -> anyhow::Result<Self> {
        let secret = {
            create_private_dir(&dirs.state_dir)?;
            load_or_create_secret(dirs)?
        };
        let credential = crate::headers::GptUpstreamCredential::new(&secret)
            .context("generated secret is not a valid header value")?;
        let base_url = format!("http://127.0.0.1:{}", upstream.port);
        let (ready_tx, ready_rx) = watch::channel(false);
        let (shutdown_tx, shutdown_rx) = watch::channel(false);
        let handle = ManagedHandle {
            base_url: base_url.clone(),
            credential: credential.clone(),
            ready: ready_rx,
        };
        let child_pgid: SharedPgid = std::sync::Arc::new(std::sync::Mutex::new(None));
        let task = tokio::spawn(supervise(
            dirs.clone(),
            upstream.clone(),
            providers,
            base_url,
            credential,
            ready_tx,
            shutdown_rx,
            tuning,
            child_pgid.clone(),
        ));
        Ok(Self {
            handle,
            shutdown_tx,
            task,
            child_pgid,
            child_record_file: dirs.upstream_child_file(),
        })
    }

    #[must_use]
    pub fn handle(&self) -> ManagedHandle {
        self.handle.clone()
    }

    /// Stops the supervision loop and terminates the child process group.
    /// Never returns with the child possibly alive: if the task does not
    /// stop within the `SIGTERM` grace plus slack, the tracked group is
    /// `SIGKILL`ed directly.
    pub async fn shutdown(mut self) {
        let _ = self.shutdown_tx.send(true);
        // Child SIGTERM grace plus slack. Every other supervision await is
        // cancellation-aware, keeping this below the service-manager budget.
        let deadline = SHUTDOWN_GRACE + Duration::from_secs(2);
        if tokio::time::timeout(deadline, &mut self.task)
            .await
            .is_err()
        {
            tracing::warn!("supervision task did not stop in time; aborting it");
            // Abort so a detached task can never spawn a child later; every
            // pre-spawn await is cancellation-aware, and there is no await
            // between spawn and pgid tracking, so aborting cannot interleave
            // past a spawn without the slot being set.
            self.task.abort();
            let _ = self.task.await;
            #[cfg(unix)]
            if let Some(pgid) = self
                .child_pgid
                .lock()
                .map_or(None, |slot| *slot)
                .filter(|pgid| *pgid > 0)
            {
                tracing::warn!("force-killing child group");
                // SAFETY: signaling a process group we created; the pgid
                // cannot be recycled while its unreaped leader exists.
                unsafe {
                    libc::killpg(pgid, libc::SIGKILL);
                }
                clear_child_record_path(&self.child_record_file);
            }
        }
    }
}

#[allow(clippy::too_many_arguments)]
async fn supervise(
    dirs: Dirs,
    upstream: UpstreamConfig,
    providers: Vec<crate::config::OpenAiProvider>,
    base_url: String,
    credential: crate::headers::GptUpstreamCredential,
    ready_tx: watch::Sender<bool>,
    mut shutdown_rx: watch::Receiver<bool>,
    tuning: Tuning,
    child_pgid: SharedPgid,
) {
    let probe_client = reqwest::Client::builder()
        .connect_timeout(Duration::from_secs(2))
        .timeout(Duration::from_secs(5))
        .build()
        .expect("probe client always builds");
    let mut backoff = tuning.backoff_initial;
    loop {
        if is_shutdown(&shutdown_rx) {
            return;
        }
        // Every fallible startup step retries here instead of failing the
        // router: acquisition (network), state prep (disk), the port-free
        // check (stale process), spawning, and readiness.
        let attempt = attempt_child(
            &dirs,
            &upstream,
            &providers,
            &base_url,
            &credential,
            &probe_client,
            &ready_tx,
            &mut shutdown_rx,
            &tuning,
            &child_pgid,
        )
        .await;
        let started_at = match attempt {
            ChildAttempt::Shutdown => return,
            ChildAttempt::Failed => None,
            ChildAttempt::Ran { started_at } => Some(started_at),
        };

        if started_at.is_some_and(|started_at| started_at.elapsed() >= tuning.backoff_reset_uptime)
        {
            backoff = tuning.backoff_initial;
        }
        if wait_or_shutdown(&mut shutdown_rx, backoff).await {
            return;
        }
        backoff = (backoff * 2).min(tuning.backoff_max);
    }
}

enum ChildAttempt {
    /// Shutdown was requested; the loop must exit.
    Shutdown,
    /// Setup failed before a child ran; back off and retry.
    Failed,
    /// A child ran (ready or not) and exited or was terminated.
    Ran { started_at: std::time::Instant },
}

#[allow(clippy::too_many_lines, clippy::too_many_arguments)]
async fn attempt_child(
    dirs: &Dirs,
    upstream: &UpstreamConfig,
    providers: &[crate::config::OpenAiProvider],
    base_url: &str,
    credential: &crate::headers::GptUpstreamCredential,
    probe_client: &reqwest::Client,
    ready_tx: &watch::Sender<bool>,
    shutdown_rx: &mut watch::Receiver<bool>,
    tuning: &Tuning,
    child_pgid: &SharedPgid,
) -> ChildAttempt {
    // Acquisition can block on a slow first-run download; stay
    // cancellation-aware so shutdown never waits behind it.
    let binary = tokio::select! {
        acquired = crate::acquire::ensure_upstream(dirs) => match acquired {
            Ok(binary) => binary,
            Err(error) => {
                tracing::error!(%error, "failed to acquire cli-proxy-api; will retry");
                return ChildAttempt::Failed;
            }
        },
        _ = shutdown_rx.changed() => return ChildAttempt::Shutdown,
    };
    let paths = match prepare_managed_state(dirs, upstream, providers) {
        Ok(paths) => paths,
        Err(error) => {
            tracing::error!(%error, "failed to prepare managed state; will retry");
            return ChildAttempt::Failed;
        }
    };
    // The port must be free before every spawn: a foreign listener here
    // would receive prompts and the injected secret. The only exception is a
    // process group whose persisted identity still matches in every field.
    if port_in_use(paths.port).await && !reap_recorded_child(dirs, paths.port).await {
        tracing::error!(
            port = paths.port,
            "port is already in use; refusing to adopt an unknown listener as the cliproxy \
             upstream. If a stale cli-proxy-api is running, stop it, or change \
             [upstreams.cliproxy] port in the config. Will retry."
        );
        return ChildAttempt::Failed;
    }

    // Last line of defense: never spawn after shutdown was requested (the
    // preceding awaits are each cancellation-aware, but re-check anyway).
    if is_shutdown(shutdown_rx) {
        return ChildAttempt::Shutdown;
    }

    let started_at = std::time::Instant::now();
    let mut child = match spawn_child(&binary, &paths).await {
        Ok(child) => child,
        Err(error) => {
            tracing::error!(%error, "failed to spawn cli-proxy-api");
            return ChildAttempt::Failed;
        }
    };
    let pgid = child.id().map(|id| i32::try_from(id).unwrap_or(0));
    let mut record = match persist_minimal_spawned_child(dirs, &binary, &child, pgid) {
        Ok(record) => record,
        Err(error) => {
            tracing::error!(%error, "failed to persist cli-proxy-api child identity");
            discard_unpersistable_child(dirs, child_pgid, &mut child, pgid).await;
            return ChildAttempt::Failed;
        }
    };
    set_pgid(child_pgid, pgid);
    if let Err(error) = enrich_spawned_child_record(dirs, &mut child, &mut record).await {
        tracing::error!(%error, "failed to persist cli-proxy-api child identity");
        discard_unpersistable_child(dirs, child_pgid, &mut child, pgid).await;
        return ChildAttempt::Failed;
    }
    tracing::info!(pid = ?child.id(), "cli-proxy-api started");

    // Readiness: authenticated /v1/models probe against our own child. The
    // probe itself is cancellation-aware — shutdown never waits behind a
    // blackholed probe.
    let ready_deadline = std::time::Instant::now() + tuning.readiness_timeout;
    let mut became_ready = false;
    let mut exited_during_startup = false;
    while std::time::Instant::now() < ready_deadline {
        if is_shutdown(shutdown_rx) {
            terminate(&mut child, pgid).await;
            clear_child_tracking(dirs, child_pgid);
            return ChildAttempt::Shutdown;
        }
        if let Ok(Some(status)) = child.try_wait() {
            tracing::error!(%status, "cli-proxy-api exited during startup");
            clear_child_tracking(dirs, child_pgid);
            exited_during_startup = true;
            break;
        }
        tokio::select! {
            ready = probe_ready(probe_client, base_url, credential) => {
                if ready {
                    became_ready = true;
                    break;
                }
            }
            _ = shutdown_rx.changed() => {
                terminate(&mut child, pgid).await;
                clear_child_tracking(dirs, child_pgid);
                return ChildAttempt::Shutdown;
            }
        }
        if wait_or_shutdown(shutdown_rx, tuning.readiness_poll).await {
            terminate(&mut child, pgid).await;
            clear_child_tracking(dirs, child_pgid);
            return ChildAttempt::Shutdown;
        }
    }
    if exited_during_startup {
        return ChildAttempt::Ran { started_at };
    }
    if became_ready {
        tracing::info!("cliproxy upstream ready");
        let _ = ready_tx.send(true);
    } else {
        // A live child that never becomes ready is a hang, not a crash:
        // terminate it and let the backoff loop start a fresh one, or GPT
        // routing would stay degraded forever.
        tracing::error!(
            log = %paths.log_file.display(),
            "cli-proxy-api did not become ready in time; restarting it (see its log)"
        );
        terminate(&mut child, pgid).await;
        clear_child_tracking(dirs, child_pgid);
        return ChildAttempt::Ran { started_at };
    }

    // Wait for exit or shutdown.
    let attempt = tokio::select! {
        status = child.wait() => {
            let _ = ready_tx.send(false);
            match status {
                Ok(status) => tracing::error!(%status, "cli-proxy-api exited; restarting"),
                Err(error) => tracing::error!(%error, "failed to wait on cli-proxy-api"),
            }
            ChildAttempt::Ran { started_at }
        }
        _ = shutdown_rx.changed() => {
            let _ = ready_tx.send(false);
            terminate(&mut child, pgid).await;
            ChildAttempt::Shutdown
        }
    };
    clear_child_tracking(dirs, child_pgid);
    attempt
}

fn persist_minimal_spawned_child(
    dirs: &Dirs,
    binary: &Path,
    child: &tokio::process::Child,
    pgid: Option<i32>,
) -> anyhow::Result<ChildRecord> {
    let record = minimal_child_record(dirs, binary, child, pgid)?;
    write_child_record(dirs, &record)?;
    Ok(record)
}

async fn enrich_spawned_child_record(
    dirs: &Dirs,
    child: &mut tokio::process::Child,
    record: &mut ChildRecord,
) -> anyhow::Result<()> {
    let deadline = std::time::Instant::now() + CHILD_IDENTITY_TIMEOUT;
    let identity = loop {
        if child.try_wait()?.is_some() {
            anyhow::bail!("cli-proxy-api exited before its identity could be persisted");
        }
        if let Ok(identity) = process_identity(record.pid)
            && identity.executable == record.executable
            && process_group(record.pid).is_ok_and(|live_pgid| live_pgid == record.pgid)
        {
            break identity;
        }
        if std::time::Instant::now() >= deadline {
            anyhow::bail!("cli-proxy-api identity did not become verifiable after spawn");
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    };
    record.start_time = Some(identity.start_time);
    write_child_record(dirs, record)
}

fn minimal_child_record(
    dirs: &Dirs,
    binary: &Path,
    child: &tokio::process::Child,
    pgid: Option<i32>,
) -> anyhow::Result<ChildRecord> {
    let child_pid = child
        .id()
        .and_then(|pid| i32::try_from(pid).ok())
        .filter(|pid| *pid > 0)
        .context("spawned child has no valid PID")?;
    let pgid = pgid
        .filter(|pgid| *pgid == child_pid)
        .context("spawned child is not the leader of the process group model-router created")?;
    Ok(ChildRecord {
        format_version: 1,
        pid: child_pid,
        pgid,
        executable: canonical_cached_executable(&dirs.cache_dir, binary)?,
        start_time: None,
    })
}

fn write_child_record(dirs: &Dirs, record: &ChildRecord) -> anyhow::Result<()> {
    let encoded = serde_json::to_vec_pretty(record).context("failed to encode child identity")?;
    write_private_atomic(&dirs.upstream_child_file(), &encoded)
        .context("failed to write child identity")
}

fn canonical_cached_executable(cache_dir: &Path, executable: &Path) -> anyhow::Result<PathBuf> {
    let executable = fs::canonicalize(executable).with_context(|| {
        format!(
            "failed to resolve cli-proxy-api executable {}",
            executable.display()
        )
    })?;
    let cache_dir = fs::canonicalize(cache_dir)
        .with_context(|| format!("failed to resolve cache dir {}", cache_dir.display()))?;
    anyhow::ensure!(
        executable.starts_with(&cache_dir),
        "cli-proxy-api executable {} is outside model-router cache dir {}",
        executable.display(),
        cache_dir.display()
    );
    Ok(executable)
}

/// Reaps only a process whose PID, process group, executable, and recorded
/// start time all still match a private record written after spawn. A minimal
/// record safely omits only the start-time check. Any ambiguity leaves the
/// listener untouched and preserves the existing refusal path.
async fn reap_recorded_child(dirs: &Dirs, port: u16) -> bool {
    let record = match load_child_record(dirs) {
        Ok(Some(record)) => record,
        Ok(None) => return false,
        Err(error) => {
            tracing::warn!(
                %error,
                "cannot verify recorded cli-proxy-api child; keeping child identity record"
            );
            return false;
        }
    };
    match verify_child_record(dirs, &record) {
        Ok(ChildRecordStatus::Verified) => {}
        Ok(ChildRecordStatus::Dead) => {
            tracing::warn!(
                pid = record.pid,
                "recorded cli-proxy-api PID is dead; clearing child identity record"
            );
            clear_child_record(dirs);
            return false;
        }
        Err(error) => {
            tracing::warn!(
                %error,
                pid = record.pid,
                "recorded child identity does not verify; keeping child identity record"
            );
            return false;
        }
    }

    tracing::warn!(
        pid = record.pid,
        pgid = record.pgid,
        port,
        "reaping identity-verified stale cli-proxy-api process group"
    );
    match verify_child_record(dirs, &record) {
        Ok(ChildRecordStatus::Verified) => {}
        Ok(ChildRecordStatus::Dead) => {
            tracing::warn!(
                pid = record.pid,
                "recorded cli-proxy-api PID died before reaping; clearing child identity record"
            );
            clear_child_record(dirs);
            return false;
        }
        Err(error) => {
            tracing::warn!(
                %error,
                pid = record.pid,
                "recorded child identity changed before reaping; keeping child identity record"
            );
            return false;
        }
    }
    // SIGKILL avoids a later signal after the group leader exits, when the
    // identity could no longer be checked against PID reuse.
    if let Err(error) = kill_stale_process_group(record.pgid) {
        tracing::warn!(
            %error,
            "failed to kill verified stale cli-proxy-api process group"
        );
        return false;
    }
    clear_child_record(dirs);

    let deadline = std::time::Instant::now() + REAPER_PORT_TIMEOUT;
    while port_in_use(port).await {
        if std::time::Instant::now() >= deadline {
            tracing::warn!(port, "port remained occupied after stale-child reaping");
            return false;
        }
        tokio::time::sleep(Duration::from_millis(25)).await;
    }
    true
}

fn load_child_record(dirs: &Dirs) -> anyhow::Result<Option<ChildRecord>> {
    let path = dirs.upstream_child_file();
    let bytes = match fs::read(&path) {
        Ok(bytes) => bytes,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(error).with_context(|| format!("failed to read {}", path.display()));
        }
    };
    anyhow::ensure!(
        bytes.len() <= 16 * 1024,
        "child identity record is too large"
    );
    serde_json::from_slice(&bytes)
        .with_context(|| format!("failed to parse {}", path.display()))
        .map(Some)
}

fn verify_child_record(dirs: &Dirs, record: &ChildRecord) -> anyhow::Result<ChildRecordStatus> {
    anyhow::ensure!(record.format_version == 1, "unknown child record format");
    anyhow::ensure!(record.pid > 0, "recorded PID is invalid");
    anyhow::ensure!(
        record.pgid == record.pid,
        "recorded process group is invalid"
    );
    if !process_is_live(record.pid).context("failed to check recorded PID liveness")? {
        return Ok(ChildRecordStatus::Dead);
    }
    let executable = canonical_cached_executable(&dirs.cache_dir, &record.executable)?;
    anyhow::ensure!(
        executable == record.executable,
        "recorded executable is not a resolved path under the model-router cache"
    );
    let identity = process_identity(record.pid).context("recorded PID is not inspectable")?;
    anyhow::ensure!(
        identity.executable == record.executable,
        "live executable does not match the record"
    );
    if let Some(start_time) = record.start_time {
        anyhow::ensure!(
            identity.start_time == start_time,
            "live process start time does not match the record"
        );
    }
    anyhow::ensure!(
        process_group(record.pid).is_ok_and(|pgid| pgid == record.pgid),
        "live process group does not match the record"
    );
    Ok(ChildRecordStatus::Verified)
}

fn clear_child_record(dirs: &Dirs) {
    clear_child_record_path(&dirs.upstream_child_file());
}

async fn discard_unpersistable_child(
    dirs: &Dirs,
    child_pgid: &SharedPgid,
    child: &mut tokio::process::Child,
    pgid: Option<i32>,
) {
    // A persistence failure may mean no usable record exists; kill the child
    // rather than risk leaving an unadoptable orphan.
    terminate(child, pgid).await;
    clear_child_tracking(dirs, child_pgid);
}

fn clear_child_tracking(dirs: &Dirs, child_pgid: &SharedPgid) {
    clear_child_record(dirs);
    set_pgid(child_pgid, None);
}

fn clear_child_record_path(path: &Path) {
    if let Err(error) = fs::remove_file(path)
        && error.kind() != std::io::ErrorKind::NotFound
    {
        tracing::warn!(%error, path = %path.display(), "failed to clear child identity record");
    }
}

#[cfg(unix)]
fn process_is_live(pid: i32) -> std::io::Result<bool> {
    // SAFETY: signal 0 only checks whether the supplied PID exists and is
    // signalable; it does not deliver a signal.
    if unsafe { libc::kill(pid, 0) } == 0 {
        return Ok(true);
    }
    let error = std::io::Error::last_os_error();
    match error.raw_os_error() {
        Some(libc::ESRCH) => Ok(false),
        Some(libc::EPERM) => Ok(true),
        _ => Err(error),
    }
}

#[cfg(not(unix))]
fn process_is_live(_pid: i32) -> std::io::Result<bool> {
    Err(std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        "process liveness checks are supported only on Unix",
    ))
}

#[cfg(unix)]
fn process_group(pid: i32) -> std::io::Result<i32> {
    // SAFETY: `getpgid` only inspects the supplied PID.
    let live_group = unsafe { libc::getpgid(pid) };
    if live_group < 0 {
        Err(std::io::Error::last_os_error())
    } else {
        Ok(live_group)
    }
}

#[cfg(not(unix))]
fn process_group(_pid: i32) -> std::io::Result<i32> {
    Err(std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        "process groups are supported only on Unix",
    ))
}

#[cfg(unix)]
fn kill_stale_process_group(pgid: i32) -> std::io::Result<()> {
    // SAFETY: the caller has positively verified the recorded identity and
    // dedicated process group immediately before this call.
    if unsafe { libc::killpg(pgid, libc::SIGKILL) } == 0 {
        Ok(())
    } else {
        Err(std::io::Error::last_os_error())
    }
}

#[cfg(not(unix))]
fn kill_stale_process_group(_pgid: i32) -> std::io::Result<()> {
    Err(std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        "process groups are supported only on Unix",
    ))
}

#[cfg(target_os = "linux")]
fn process_identity(pid: i32) -> std::io::Result<ProcessIdentity> {
    let executable = fs::read_link(format!("/proc/{pid}/exe"))?;
    let stat = fs::read_to_string(format!("/proc/{pid}/stat"))?;
    // The parenthesized comm field may itself contain spaces or `)`, so split
    // after its final closing parenthesis. The remainder starts at field 3;
    // process start time is field 22, hence index 19.
    let fields = stat
        .rsplit_once(") ")
        .map(|(_, fields)| fields)
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::InvalidData, "invalid proc stat"))?;
    let start_time = fields
        .split_whitespace()
        .nth(19)
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::InvalidData, "missing start time"))?
        .parse()
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error))?;
    Ok(ProcessIdentity {
        executable,
        start_time,
    })
}

#[cfg(target_os = "macos")]
fn process_identity(pid: i32) -> std::io::Result<ProcessIdentity> {
    use std::ffi::OsStr;
    use std::os::unix::ffi::OsStrExt as _;

    // SAFETY: both calls receive correctly sized, writable buffers; successful
    // byte counts are checked before any fields or path bytes are read.
    unsafe {
        let mut info = std::mem::zeroed::<libc::proc_bsdinfo>();
        let info_size = i32::try_from(std::mem::size_of::<libc::proc_bsdinfo>())
            .expect("proc_bsdinfo size fits i32");
        let read = libc::proc_pidinfo(
            pid,
            libc::PROC_PIDTBSDINFO,
            0,
            std::ptr::addr_of_mut!(info).cast(),
            info_size,
        );
        if read != info_size {
            return Err(std::io::Error::last_os_error());
        }
        let mut path = vec![0_u8; libc::PROC_PIDPATHINFO_MAXSIZE as usize];
        let path_len = libc::proc_pidpath(
            pid,
            path.as_mut_ptr().cast(),
            u32::try_from(path.len()).expect("process path buffer fits u32"),
        );
        if path_len <= 0 {
            return Err(std::io::Error::last_os_error());
        }
        path.truncate(usize::try_from(path_len).expect("positive path length fits usize"));
        let start_time = info
            .pbi_start_tvsec
            .checked_mul(1_000_000)
            .and_then(|seconds| seconds.checked_add(info.pbi_start_tvusec))
            .ok_or_else(|| {
                std::io::Error::new(std::io::ErrorKind::InvalidData, "start time overflow")
            })?;
        Ok(ProcessIdentity {
            executable: PathBuf::from(OsStr::from_bytes(&path)),
            start_time,
        })
    }
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
fn process_identity(_pid: i32) -> std::io::Result<ProcessIdentity> {
    Err(std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        "process identity is supported only on macOS and Linux",
    ))
}

fn set_pgid(slot: &SharedPgid, pgid: impl Into<Option<i32>>) {
    if let Ok(mut guard) = slot.lock() {
        *guard = pgid.into();
    }
}

/// True when shutdown was requested — or the `Supervisor` was dropped
/// (sender gone), which must also stop the loop or it would spin hot.
fn is_shutdown(shutdown_rx: &watch::Receiver<bool>) -> bool {
    shutdown_rx.has_changed().is_err() || *shutdown_rx.borrow()
}

/// Returns true when shutdown was requested during the wait.
async fn wait_or_shutdown(shutdown_rx: &mut watch::Receiver<bool>, wait: Duration) -> bool {
    tokio::select! {
        () = tokio::time::sleep(wait) => is_shutdown(shutdown_rx),
        result = shutdown_rx.changed() => result.is_err() || *shutdown_rx.borrow(),
    }
}

async fn spawn_child(
    binary: &PathBuf,
    paths: &ManagedPaths,
) -> anyhow::Result<tokio::process::Child> {
    let log = tokio::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&paths.log_file)
        .await
        .with_context(|| format!("failed to open {}", paths.log_file.display()))?;
    let mut log_for_stamp = log.try_clone().await?;
    let stamp = format!(
        "\n--- model-router spawning cli-proxy-api at {} ---\n",
        chrono::Utc::now().to_rfc3339()
    );
    let _ = log_for_stamp.write_all(stamp.as_bytes()).await;
    let log_std = log.into_std().await;
    let stderr_log = log_std.try_clone().context("failed to clone log handle")?;

    let mut command = tokio::process::Command::new(binary);
    command
        .arg("-config")
        .arg(&paths.upstream_config)
        .stdin(Stdio::null())
        .stdout(log_std)
        .stderr(stderr_log);
    #[cfg(unix)]
    {
        // New process group so shutdown can kill the child and anything it
        // spawns without touching the router's own group.
        command.process_group(0);
    }
    command.spawn().context("failed to spawn cli-proxy-api")
}

async fn terminate(child: &mut tokio::process::Child, pgid: Option<i32>) {
    #[cfg(unix)]
    if let Some(pgid) = pgid.filter(|pgid| *pgid > 0) {
        // SAFETY: signaling a process group we created.
        unsafe {
            libc::killpg(pgid, libc::SIGTERM);
        }
        if matches!(
            tokio::time::timeout(SHUTDOWN_GRACE, child.wait()).await,
            Ok(Ok(_))
        ) {
            return;
        }
        tracing::warn!("cli-proxy-api ignored SIGTERM; killing");
        // SAFETY: as above.
        unsafe {
            libc::killpg(pgid, libc::SIGKILL);
        }
        let _ = child.wait().await;
        return;
    }
    let _ = child.kill().await;
}

/// Authenticated readiness probe: /v1/models with the injected credential
/// must return 200 JSON. A bare TCP accept is never treated as readiness.
/// Uses the same `GptUpstreamCredential` as the proxy request path so the
/// probe can never validate a different auth shape than real requests use.
async fn probe_ready(
    client: &reqwest::Client,
    base_url: &str,
    credential: &crate::headers::GptUpstreamCredential,
) -> bool {
    let Ok(response) = credential
        .apply(client.get(format!("{base_url}/v1/models")))
        .send()
        .await
    else {
        return false;
    };
    if !response.status().is_success() {
        return false;
    }
    let Ok(body) = response.bytes().await else {
        return false;
    };
    serde_json::from_slice::<serde_json::Value>(&body).is_ok_and(|value| value.is_object())
}

/// True when something is already listening on the loopback port.
async fn port_in_use(port: u16) -> bool {
    tokio::net::TcpStream::connect(("127.0.0.1", port))
        .await
        .is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaml_config_contains_hardening_flags() {
        let yaml = upstream_config_yaml(8317, std::path::Path::new("/tmp/auth"), "secret123", &[]);
        assert!(yaml.contains("host: \"127.0.0.1\""));
        assert!(yaml.contains("disable-claude-cloak-mode: true"));
        assert!(yaml.contains("disable-control-panel: true"));
        assert!(yaml.contains("usage-statistics-enabled: false"));
        assert!(yaml.contains("- \"secret123\""));
        assert!(yaml.contains("auth-dir: \"/tmp/auth\""));
    }

    fn test_provider(name: &str, routing_id: &str) -> crate::config::OpenAiProvider {
        crate::config::OpenAiProvider {
            name: name.to_string(),
            base_url: "https://api.example.com/v1".to_string(),
            api_key: Some("test-key".to_string()),
            models: vec![crate::config::ProviderModel {
                name: format!("upstream/{routing_id}"),
                routing_id: routing_id.to_string(),
                display_name: routing_id.to_string(),
            }],
        }
    }

    #[test]
    fn generated_yaml_parses_with_and_without_providers() {
        for providers in [
            Vec::new(),
            vec![
                test_provider("fireworks", "kimi-k2.7"),
                test_provider("together", "glm-5.2"),
            ],
        ] {
            let yaml = upstream_config_yaml(
                8317,
                std::path::Path::new("/tmp/auth"),
                "s3cret",
                &providers,
            );
            let value: serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap();
            assert_eq!(value["port"], serde_yaml::Value::from(8317));
            assert_eq!(value["auth-dir"], serde_yaml::Value::from("/tmp/auth"));
            let compat = &value["openai-compatibility"];
            if providers.is_empty() {
                assert!(compat.is_null(), "no providers must mean no compat section");
                continue;
            }
            let entries = compat.as_sequence().unwrap();
            assert_eq!(entries.len(), 2);
            assert_eq!(entries[0]["name"], serde_yaml::Value::from("fireworks"));
            assert_eq!(
                entries[0]["base-url"],
                serde_yaml::Value::from("https://api.example.com/v1")
            );
            assert_eq!(
                entries[0]["api-key-entries"][0]["api-key"],
                serde_yaml::Value::from("test-key")
            );
            assert_eq!(
                entries[0]["models"][0]["name"],
                serde_yaml::Value::from("upstream/kimi-k2.7")
            );
            assert_eq!(
                entries[0]["models"][0]["alias"],
                serde_yaml::Value::from("openai-compat--kimi-k2.7")
            );
            assert_eq!(
                entries[1]["models"][0]["alias"],
                serde_yaml::Value::from("openai-compat--glm-5.2")
            );
        }
    }

    #[test]
    fn hostile_scalars_survive_yaml_round_trip() {
        let hostile = [
            "quo\"te",
            "back\\slash",
            "colon: hash # dash - question ?",
            "  leading and trailing  ",
            "uni\u{e9}code \u{1f980}",
            "line\nfeed\ttab",
            "del\u{7f}c1\u{9f}",
            "literal backslash-u \\u007f stays literal",
        ];
        // Validation rejects some of these in real configs; the emitter must
        // stay correct regardless so safety never depends on two layers
        // agreeing.
        let mut provider = test_provider("p", "r");
        for value in hostile {
            provider.api_key = Some(value.to_string());
            provider.models[0].name = value.to_string();
            let yaml =
                upstream_config_yaml(1, std::path::Path::new(value), value, &[provider.clone()]);
            let parsed: serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap();
            assert_eq!(
                parsed["auth-dir"],
                serde_yaml::Value::from(value),
                "{value}"
            );
            assert_eq!(
                parsed["api-keys"][0],
                serde_yaml::Value::from(value),
                "{value}"
            );
            assert_eq!(
                parsed["openai-compatibility"][0]["api-key-entries"][0]["api-key"],
                serde_yaml::Value::from(value),
                "{value}"
            );
            assert_eq!(
                parsed["openai-compatibility"][0]["models"][0]["name"],
                serde_yaml::Value::from(value),
                "{value}"
            );
        }
    }

    #[test]
    fn prepare_managed_state_writes_providers_to_disk() {
        let root = tempfile::tempdir().unwrap();
        let dirs = dirs_with_fake_upstream(root.path(), "ready");
        let upstream = UpstreamConfig::default();
        let providers = vec![test_provider("fireworks", "kimi-k2.7")];
        let paths = prepare_managed_state(&dirs, &upstream, &providers).unwrap();
        let on_disk = std::fs::read_to_string(&paths.upstream_config).unwrap();
        let parsed: serde_yaml::Value = serde_yaml::from_str(&on_disk).unwrap();
        assert_eq!(
            parsed["openai-compatibility"][0]["models"][0]["alias"],
            serde_yaml::Value::from("openai-compat--kimi-k2.7")
        );
        // Regenerating without providers removes the section (stale provider
        // config must not survive a config edit + restart).
        let paths = prepare_managed_state(&dirs, &upstream, &[]).unwrap();
        let on_disk = std::fs::read_to_string(&paths.upstream_config).unwrap();
        let parsed: serde_yaml::Value = serde_yaml::from_str(&on_disk).unwrap();
        assert!(parsed["openai-compatibility"].is_null());
    }

    #[tokio::test]
    async fn port_in_use_detects_listener() {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();
        assert!(port_in_use(port).await);
        drop(listener);
    }

    fn fast_tuning() -> Tuning {
        Tuning {
            readiness_timeout: Duration::from_millis(300),
            readiness_poll: Duration::from_millis(50),
            backoff_initial: Duration::from_millis(50),
            backoff_max: Duration::from_millis(100),
            backoff_reset_uptime: Duration::from_mins(1),
        }
    }

    /// Tuning for tests whose child is expected to become ready: under a
    /// loaded machine a 300ms readiness window can expire before the child
    /// even binds, sending the supervisor into kill/backoff/respawn cycles.
    fn ready_tuning() -> Tuning {
        Tuning {
            readiness_timeout: Duration::from_secs(10),
            ..fast_tuning()
        }
    }

    /// Polls `condition` until it holds or a deadline generous enough for a
    /// heavily loaded machine passes. Returns whether it held.
    async fn wait_for(mut condition: impl AsyncFnMut() -> bool) -> bool {
        let deadline = std::time::Instant::now() + Duration::from_secs(30);
        loop {
            if condition().await {
                return true;
            }
            if std::time::Instant::now() >= deadline {
                return false;
            }
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    }

    fn dirs_with_fake_upstream(root: &std::path::Path, mode: &str) -> Dirs {
        let dirs = Dirs {
            config_dir: root.join("config"),
            state_dir: root.join("state"),
            cache_dir: root.join("cache"),
        };
        let binary = dirs.upstream_binary(crate::acquire::UPSTREAM_VERSION);
        std::fs::create_dir_all(binary.parent().unwrap()).unwrap();
        std::fs::create_dir_all(&dirs.state_dir).unwrap();
        std::fs::write(dirs.state_dir.join("test-mode"), mode).unwrap();
        std::fs::copy(fake_upstream_binary(), &binary).unwrap();
        dirs
    }

    fn fake_upstream_binary() -> &'static Path {
        static BINARY: std::sync::OnceLock<PathBuf> = std::sync::OnceLock::new();
        BINARY.get_or_init(|| {
            let root = tempfile::Builder::new()
                .prefix("model-router-fake-upstream")
                .tempdir()
                .unwrap()
                .keep();
            let source = root.join("fake-upstream.rs");
            let binary = root.join("fake-upstream");
            std::fs::write(&source, FAKE_UPSTREAM_SOURCE).unwrap();
            let output = std::process::Command::new("rustc")
                .args(["--edition=2024", "-O"])
                .arg(&source)
                .arg("-o")
                .arg(&binary)
                .output()
                .unwrap();
            assert!(
                output.status.success(),
                "failed to compile fake upstream: {}",
                String::from_utf8_lossy(&output.stderr)
            );
            binary
        })
    }

    const FAKE_UPSTREAM_SOURCE: &str = r#"
use std::fs::{self, OpenOptions};
use std::io::{Read as _, Write as _};
use std::net::TcpListener;
use std::path::PathBuf;
use std::time::Duration;

unsafe extern "C" { fn signal(signal: i32, handler: usize) -> usize; }

fn main() {
    let args = std::env::args_os().collect::<Vec<_>>();
    let config = args.windows(2).find(|pair| pair[0] == "-config")
        .map(|pair| PathBuf::from(&pair[1])).expect("-config path");
    let state = config.parent().expect("state dir");
    let mode = fs::read_to_string(state.join("test-mode")).expect("test mode");
    // Install the SIGTERM-ignore handler BEFORE the pid becomes observable:
    // tests synchronize on child-pid, and shutdown must find a child that
    // already ignores SIGTERM or the SIGKILL escalation is never exercised.
    if mode.trim() == "ignore" {
        unsafe { signal(15, 1); }
    }
    writeln!(OpenOptions::new().create(true).append(true)
        .open(state.join("spawns")).unwrap(), "{}", std::process::id()).unwrap();
    fs::write(state.join("child-pid"), std::process::id().to_string()).unwrap();
    if mode.trim() != "ready" {
        loop { std::thread::sleep(Duration::from_secs(60)); }
    }
    let yaml = fs::read_to_string(config).unwrap();
    let port = yaml.lines().find_map(|line| line.strip_prefix("port: "))
        .unwrap().parse::<u16>().unwrap();
    let listener = TcpListener::bind(("127.0.0.1", port)).unwrap();
    for stream in listener.incoming() {
        let mut stream = stream.unwrap();
        let mut request = [0_u8; 4096];
        let _ = stream.read(&mut request);
        stream.write_all(b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 2\r\nConnection: close\r\n\r\n{}").unwrap();
    }
}
"#;

    fn free_port() -> u16 {
        std::net::TcpListener::bind("127.0.0.1:0")
            .unwrap()
            .local_addr()
            .unwrap()
            .port()
    }

    #[tokio::test]
    async fn live_but_unready_child_is_terminated_and_respawned() {
        let root = tempfile::tempdir().unwrap();
        // A child that runs but never serves the port: readiness must time
        // out, the supervisor must kill it and spawn a fresh one.
        let dirs = dirs_with_fake_upstream(root.path(), "unready");
        let spawn_log = dirs.state_dir.join("spawns");
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        let supervisor = Supervisor::start(&dirs, &upstream, Vec::new(), fast_tuning()).unwrap();
        let handle = supervisor.handle();
        let restarted = wait_for(async || {
            std::fs::read_to_string(&spawn_log)
                .unwrap_or_default()
                .lines()
                .count()
                >= 2
        })
        .await;
        assert!(!handle.is_ready());
        assert!(
            restarted,
            "expected the hung child to be restarted, saw {} spawn(s)",
            std::fs::read_to_string(&spawn_log)
                .unwrap_or_default()
                .lines()
                .count()
        );
        supervisor.shutdown().await;
    }

    #[tokio::test]
    async fn shutdown_never_leaves_a_live_child() {
        let root = tempfile::tempdir().unwrap();
        // A child that ignores SIGTERM: shutdown must escalate to SIGKILL
        // and never return with the process alive.
        let dirs = dirs_with_fake_upstream(root.path(), "ignore");
        let pid_file = dirs.state_dir.join("child-pid");
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        // The generous readiness timeout keeps the supervisor's own
        // readiness-expiry terminate from killing the child first, which
        // would let the assertion pass without exercising shutdown at all.
        let supervisor = Supervisor::start(&dirs, &upstream, Vec::new(), ready_tuning()).unwrap();
        // Wait until a spawned child is observably LIVE (a fixed sleep can
        // miss the spawn under load, passing vacuously); the fake installs
        // its SIGTERM-ignore handler before publishing its pid, so a live
        // pid here guarantees shutdown must escalate to SIGKILL.
        let child_pid = async || {
            std::fs::read_to_string(&pid_file)
                .ok()
                .and_then(|text| text.trim().parse::<i32>().ok())
        };
        assert!(
            wait_for(async || {
                // SAFETY: signal 0 only checks liveness.
                child_pid()
                    .await
                    .is_some_and(|pid| unsafe { libc::kill(pid, 0) } == 0)
            })
            .await,
            "child never spawned"
        );
        supervisor.shutdown().await;
        let pid = child_pid().await.unwrap();
        // SAFETY: signal 0 only checks liveness.
        let alive = unsafe { libc::kill(pid, 0) } == 0;
        assert!(!alive, "child {pid} survived shutdown");
    }

    #[tokio::test]
    async fn occupied_port_prevents_any_spawn() {
        let root = tempfile::tempdir().unwrap();
        let dirs = dirs_with_fake_upstream(root.path(), "unready");
        let spawn_log = dirs.state_dir.join("spawns");
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let upstream = UpstreamConfig {
            port: listener.local_addr().unwrap().port(),
            ..UpstreamConfig::default()
        };
        let supervisor = Supervisor::start(&dirs, &upstream, Vec::new(), fast_tuning()).unwrap();
        tokio::time::sleep(Duration::from_millis(600)).await;
        assert!(
            !spawn_log.exists(),
            "the supervisor must never spawn while a foreign listener holds the port"
        );
        assert!(!supervisor.handle().is_ready());
        supervisor.shutdown().await;
        drop(listener);
    }

    #[tokio::test]
    async fn recorded_leaked_child_is_reaped_and_respawned() {
        let root = tempfile::tempdir().unwrap();
        let dirs = dirs_with_fake_upstream(root.path(), "ready");
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        let paths = prepare_managed_state(&dirs, &upstream, &[]).unwrap();
        let binary = dirs.upstream_binary(crate::acquire::UPSTREAM_VERSION);
        let mut leaked = spawn_child(&binary, &paths).await.unwrap();
        let leaked_pid = i32::try_from(leaked.id().unwrap()).unwrap();
        let mut record =
            persist_minimal_spawned_child(&dirs, &binary, &leaked, Some(leaked_pid)).unwrap();
        enrich_spawned_child_record(&dirs, &mut leaked, &mut record)
            .await
            .unwrap();
        assert!(wait_for(async || port_in_use(upstream.port).await).await);

        let supervisor = Supervisor::start(&dirs, &upstream, Vec::new(), ready_tuning()).unwrap();
        let replaced = wait_for(async || {
            std::fs::read_to_string(dirs.state_dir.join("spawns"))
                .unwrap_or_default()
                .lines()
                .count()
                >= 2
                && supervisor.handle().is_ready()
        })
        .await;
        assert!(replaced, "fresh child never became ready");
        assert!(
            std::fs::read_to_string(dirs.state_dir.join("spawns"))
                .unwrap()
                .lines()
                .count()
                >= 2,
            "stale child was not replaced"
        );
        leaked.wait().await.unwrap();
        assert_ne!(
            std::fs::read_to_string(dirs.state_dir.join("child-pid"))
                .unwrap()
                .trim()
                .parse::<i32>()
                .unwrap(),
            leaked_pid
        );
        supervisor.shutdown().await;
    }

    #[tokio::test]
    async fn minimal_recorded_child_is_reaped() {
        let root = tempfile::tempdir().unwrap();
        let dirs = dirs_with_fake_upstream(root.path(), "ready");
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        let paths = prepare_managed_state(&dirs, &upstream, &[]).unwrap();
        let binary = dirs.upstream_binary(crate::acquire::UPSTREAM_VERSION);
        let mut leaked = spawn_child(&binary, &paths).await.unwrap();
        let leaked_pid = i32::try_from(leaked.id().unwrap()).unwrap();
        let record =
            persist_minimal_spawned_child(&dirs, &binary, &leaked, Some(leaked_pid)).unwrap();
        assert_eq!(record.start_time, None);
        assert!(wait_for(async || port_in_use(upstream.port).await).await);

        assert!(reap_recorded_child(&dirs, upstream.port).await);
        leaked.wait().await.unwrap();
        assert!(!dirs.upstream_child_file().exists());
    }

    #[tokio::test]
    async fn dead_pid_child_record_is_cleared() {
        let root = tempfile::tempdir().unwrap();
        let dirs = dirs_with_fake_upstream(root.path(), "unready");
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        let paths = prepare_managed_state(&dirs, &upstream, &[]).unwrap();
        let binary = dirs.upstream_binary(crate::acquire::UPSTREAM_VERSION);
        let mut child = spawn_child(&binary, &paths).await.unwrap();
        let child_pid = i32::try_from(child.id().unwrap()).unwrap();
        persist_minimal_spawned_child(&dirs, &binary, &child, Some(child_pid)).unwrap();
        child.kill().await.unwrap();
        let _ = child.wait().await;

        assert!(!reap_recorded_child(&dirs, upstream.port).await);
        assert!(!dirs.upstream_child_file().exists());
    }

    #[tokio::test]
    async fn identity_mismatch_is_never_killed_or_adopted() {
        let root = tempfile::tempdir().unwrap();
        let dirs = dirs_with_fake_upstream(root.path(), "unready");
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let upstream = UpstreamConfig {
            port: listener.local_addr().unwrap().port(),
            ..UpstreamConfig::default()
        };
        let mut foreign = tokio::process::Command::new("sleep");
        foreign.arg("60").process_group(0);
        let mut foreign = foreign.spawn().unwrap();
        let foreign_pid = i32::try_from(foreign.id().unwrap()).unwrap();
        let identity = process_identity(foreign_pid).unwrap();
        let mismatched = ChildRecord {
            format_version: 1,
            pid: foreign_pid,
            pgid: foreign_pid,
            executable: fs::canonicalize(dirs.upstream_binary(crate::acquire::UPSTREAM_VERSION))
                .unwrap(),
            start_time: Some(identity.start_time),
        };
        write_private_atomic(
            &dirs.upstream_child_file(),
            &serde_json::to_vec(&mismatched).unwrap(),
        )
        .unwrap();

        let supervisor = Supervisor::start(&dirs, &upstream, Vec::new(), fast_tuning()).unwrap();
        tokio::time::sleep(Duration::from_millis(600)).await;
        assert!(
            foreign.try_wait().unwrap().is_none(),
            "mismatched process was killed"
        );
        assert!(
            port_in_use(upstream.port).await,
            "foreign listener was disturbed"
        );
        assert!(!dirs.state_dir.join("spawns").exists());
        assert!(
            dirs.upstream_child_file().exists(),
            "ambiguous live-process records must be preserved"
        );
        supervisor.shutdown().await;
        foreign.kill().await.unwrap();
        let _ = foreign.wait().await;
    }

    #[tokio::test]
    async fn child_record_is_cleared_after_clean_terminate() {
        let root = tempfile::tempdir().unwrap();
        let dirs = dirs_with_fake_upstream(root.path(), "ready");
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        let supervisor = Supervisor::start(&dirs, &upstream, Vec::new(), ready_tuning()).unwrap();
        assert!(
            wait_for(async || {
                supervisor.handle().is_ready() && dirs.upstream_child_file().exists()
            })
            .await,
            "child never became ready with a persisted record"
        );

        supervisor.shutdown().await;

        assert!(!dirs.upstream_child_file().exists());
    }
}
