//! Managed-mode supervision of the `CLIProxyAPI` child process.
//!
//! Ownership rules (from the reviewed plan): the child port must be FREE
//! before spawning; readiness is an authenticated application-level probe,
//! never a bare TCP accept; the exact child PID/process group is tracked and
//! killed on shutdown; restarts back off exponentially with a cap and reset
//! after a healthy stretch.

use std::path::PathBuf;
use std::process::Stdio;
use std::time::Duration;

use anyhow::Context;
use tokio::io::AsyncWriteExt;
use tokio::sync::watch;

use crate::config::UpstreamConfig;
use crate::state::{
    Dirs, create_private_dir, import_legacy_auth, load_or_create_secret, write_private_atomic,
};

const SHUTDOWN_GRACE: Duration = Duration::from_secs(5);

/// Timing knobs, overridable in tests.
#[derive(Clone, Debug)]
pub struct Tuning {
    pub readiness_timeout: Duration,
    pub readiness_poll: Duration,
    pub backoff_initial: Duration,
    pub backoff_max: Duration,
    /// Uptime after which the backoff resets (the child was genuinely healthy).
    pub backoff_reset_uptime: Duration,
}

impl Default for Tuning {
    fn default() -> Self {
        Self {
            readiness_timeout: Duration::from_secs(20),
            readiness_poll: Duration::from_millis(250),
            backoff_initial: Duration::from_secs(1),
            backoff_max: Duration::from_secs(30),
            backoff_reset_uptime: Duration::from_mins(1),
        }
    }
}

/// What the request path needs from managed mode.
#[derive(Clone)]
pub struct ManagedHandle {
    pub base_url: String,
    pub credential: crate::headers::GptUpstreamCredential,
    ready: watch::Receiver<bool>,
}

impl ManagedHandle {
    #[must_use]
    pub fn is_ready(&self) -> bool {
        *self.ready.borrow()
    }
}

/// Owns the supervision task; dropping does NOT kill the child — call
/// [`Supervisor::shutdown`] from the serve teardown path.
pub struct Supervisor {
    handle: ManagedHandle,
    shutdown_tx: watch::Sender<bool>,
    task: tokio::task::JoinHandle<()>,
    /// Live child's process group, shared with the supervision task so
    /// [`Supervisor::shutdown`] can force-kill it if the task does not stop
    /// in time (the pgid cannot be recycled while the child is unreaped).
    child_pgid: SharedPgid,
}

type SharedPgid = std::sync::Arc<std::sync::Mutex<Option<i32>>>;

/// Renders the `CLIProxyAPI` YAML config the router owns in managed mode.
/// Mirrors the config validated in live experiments: loopback bind, dedicated
/// auth dir, single local api key, cloak/control-panel/telemetry disabled.
#[must_use]
pub fn upstream_config_yaml(port: u16, auth_dir: &std::path::Path, secret: &str) -> String {
    format!(
        r#"# Generated by model-router; edits are overwritten on every managed start.
host: "127.0.0.1"
port: {port}

auth-dir: "{auth_dir}"

api-keys:
  - "{secret}"

remote-management:
  allow-remote: false
  secret-key: ""
  disable-control-panel: true

debug: false
logging-to-file: false
usage-statistics-enabled: false

disable-claude-cloak-mode: true

routing:
  strategy: "round-robin"
  session-affinity: false
"#,
        auth_dir = auth_dir.display()
    )
}

/// Prepares managed-mode state on disk and returns the paths involved.
/// Idempotent; shared by `serve`, `login`, and `doctor`.
///
/// # Errors
/// Returns an error when directories, the secret, or the config cannot be
/// created.
pub fn prepare_managed_state(
    dirs: &Dirs,
    upstream: &UpstreamConfig,
) -> anyhow::Result<ManagedPaths> {
    create_private_dir(&dirs.state_dir)?;
    create_private_dir(&dirs.auth_dir())?;
    create_private_dir(&dirs.log_dir())?;
    let secret = load_or_create_secret(dirs)?;
    import_legacy_auth(dirs)?;
    let yaml = upstream_config_yaml(upstream.port, &dirs.auth_dir(), &secret);
    write_private_atomic(&dirs.upstream_config_file(), yaml.as_bytes())?;
    Ok(ManagedPaths {
        upstream_config: dirs.upstream_config_file(),
        auth_dir: dirs.auth_dir(),
        log_file: dirs.log_dir().join("cliproxyapi.log"),
        secret,
        port: upstream.port,
    })
}

pub struct ManagedPaths {
    pub upstream_config: PathBuf,
    pub auth_dir: PathBuf,
    pub log_file: PathBuf,
    pub secret: String,
    pub port: u16,
}

impl Supervisor {
    /// Starts the supervision loop. Only cheap local state (secret,
    /// directories) is prepared up front; acquisition, the port-free check,
    /// spawning, and readiness all run — and retry with backoff — INSIDE the
    /// loop, so a failing codex upstream never takes down the Claude gateway.
    ///
    /// # Errors
    /// Returns an error only when local state (directories, the create-once
    /// secret) cannot be prepared.
    pub fn start(dirs: &Dirs, upstream: &UpstreamConfig, tuning: Tuning) -> anyhow::Result<Self> {
        let secret = {
            create_private_dir(&dirs.state_dir)?;
            load_or_create_secret(dirs)?
        };
        let credential = crate::headers::GptUpstreamCredential::new(&secret)
            .context("generated secret is not a valid header value")?;
        let base_url = format!("http://127.0.0.1:{}", upstream.port);
        let (ready_tx, ready_rx) = watch::channel(false);
        let (shutdown_tx, shutdown_rx) = watch::channel(false);
        let handle = ManagedHandle {
            base_url: base_url.clone(),
            credential: credential.clone(),
            ready: ready_rx,
        };
        let child_pgid: SharedPgid = std::sync::Arc::new(std::sync::Mutex::new(None));
        let task = tokio::spawn(supervise(
            dirs.clone(),
            upstream.clone(),
            base_url,
            credential,
            ready_tx,
            shutdown_rx,
            tuning,
            child_pgid.clone(),
        ));
        Ok(Self {
            handle,
            shutdown_tx,
            task,
            child_pgid,
        })
    }

    #[must_use]
    pub fn handle(&self) -> ManagedHandle {
        self.handle.clone()
    }

    /// Stops the supervision loop and terminates the child process group.
    /// Never returns with the child possibly alive: if the task does not
    /// stop within the deadline (worst case: an in-flight probe plus the
    /// `SIGTERM` grace), the tracked group is `SIGKILL`ed directly.
    pub async fn shutdown(mut self) {
        let _ = self.shutdown_tx.send(true);
        // Probe timeout (5s) + SIGTERM grace (5s) + slack.
        let deadline = SHUTDOWN_GRACE * 2 + Duration::from_secs(2);
        if tokio::time::timeout(deadline, &mut self.task)
            .await
            .is_err()
        {
            tracing::warn!("supervision task did not stop in time; aborting it");
            // Abort so a detached task can never spawn a child later; every
            // pre-spawn await is cancellation-aware, and there is no await
            // between spawn and pgid tracking, so aborting cannot interleave
            // past a spawn without the slot being set.
            self.task.abort();
            let _ = self.task.await;
            #[cfg(unix)]
            if let Some(pgid) = self
                .child_pgid
                .lock()
                .map_or(None, |slot| *slot)
                .filter(|pgid| *pgid > 0)
            {
                tracing::warn!("force-killing child group");
                // SAFETY: signaling a process group we created; the pgid
                // cannot be recycled while its unreaped leader exists.
                unsafe {
                    libc::killpg(pgid, libc::SIGKILL);
                }
            }
        }
    }
}

#[allow(clippy::too_many_arguments)]
async fn supervise(
    dirs: Dirs,
    upstream: UpstreamConfig,
    base_url: String,
    credential: crate::headers::GptUpstreamCredential,
    ready_tx: watch::Sender<bool>,
    mut shutdown_rx: watch::Receiver<bool>,
    tuning: Tuning,
    child_pgid: SharedPgid,
) {
    let probe_client = reqwest::Client::builder()
        .connect_timeout(Duration::from_secs(2))
        .timeout(Duration::from_secs(5))
        .build()
        .expect("probe client always builds");
    let mut backoff = tuning.backoff_initial;
    loop {
        if is_shutdown(&shutdown_rx) {
            return;
        }
        // Every fallible startup step retries here instead of failing the
        // router: acquisition (network), state prep (disk), the port-free
        // check (stale process), spawning, and readiness.
        let attempt = attempt_child(
            &dirs,
            &upstream,
            &base_url,
            &credential,
            &probe_client,
            &ready_tx,
            &mut shutdown_rx,
            &tuning,
            &child_pgid,
        )
        .await;
        let started_at = match attempt {
            ChildAttempt::Shutdown => return,
            ChildAttempt::Failed => None,
            ChildAttempt::Ran { started_at } => Some(started_at),
        };

        if started_at.is_some_and(|started_at| started_at.elapsed() >= tuning.backoff_reset_uptime)
        {
            backoff = tuning.backoff_initial;
        }
        if wait_or_shutdown(&mut shutdown_rx, backoff).await {
            return;
        }
        backoff = (backoff * 2).min(tuning.backoff_max);
    }
}

enum ChildAttempt {
    /// Shutdown was requested; the loop must exit.
    Shutdown,
    /// Setup failed before a child ran; back off and retry.
    Failed,
    /// A child ran (ready or not) and exited or was terminated.
    Ran { started_at: std::time::Instant },
}

#[allow(clippy::too_many_lines, clippy::too_many_arguments)]
async fn attempt_child(
    dirs: &Dirs,
    upstream: &UpstreamConfig,
    base_url: &str,
    credential: &crate::headers::GptUpstreamCredential,
    probe_client: &reqwest::Client,
    ready_tx: &watch::Sender<bool>,
    shutdown_rx: &mut watch::Receiver<bool>,
    tuning: &Tuning,
    child_pgid: &SharedPgid,
) -> ChildAttempt {
    // Acquisition can block on a slow first-run download; stay
    // cancellation-aware so shutdown never waits behind it.
    let binary = tokio::select! {
        acquired = crate::acquire::ensure_upstream(dirs) => match acquired {
            Ok(binary) => binary,
            Err(error) => {
                tracing::error!(%error, "failed to acquire cli-proxy-api; will retry");
                return ChildAttempt::Failed;
            }
        },
        _ = shutdown_rx.changed() => return ChildAttempt::Shutdown,
    };
    let paths = match prepare_managed_state(dirs, upstream) {
        Ok(paths) => paths,
        Err(error) => {
            tracing::error!(%error, "failed to prepare managed state; will retry");
            return ChildAttempt::Failed;
        }
    };
    // The port must be free before every spawn: a foreign listener here
    // would receive prompts and the injected secret.
    if port_in_use(paths.port).await {
        tracing::error!(
            port = paths.port,
            "port is already in use; refusing to adopt an unknown listener as the codex \
             upstream. If a stale cli-proxy-api is running, stop it, or change \
             [upstreams.codex] port in the config. Will retry."
        );
        return ChildAttempt::Failed;
    }

    // Last line of defense: never spawn after shutdown was requested (the
    // preceding awaits are each cancellation-aware, but re-check anyway).
    if is_shutdown(shutdown_rx) {
        return ChildAttempt::Shutdown;
    }

    let started_at = std::time::Instant::now();
    let mut child = match spawn_child(&binary, &paths).await {
        Ok(child) => child,
        Err(error) => {
            tracing::error!(%error, "failed to spawn cli-proxy-api");
            return ChildAttempt::Failed;
        }
    };
    let pgid = child.id().map(|id| i32::try_from(id).unwrap_or(0));
    set_pgid(child_pgid, pgid);
    tracing::info!(pid = ?child.id(), "cli-proxy-api started");

    // Readiness: authenticated /v1/models probe against our own child. The
    // probe itself is cancellation-aware — shutdown never waits behind a
    // blackholed probe.
    let ready_deadline = std::time::Instant::now() + tuning.readiness_timeout;
    let mut became_ready = false;
    let mut exited_during_startup = false;
    while std::time::Instant::now() < ready_deadline {
        if is_shutdown(shutdown_rx) {
            terminate(&mut child, pgid).await;
            set_pgid(child_pgid, None);
            return ChildAttempt::Shutdown;
        }
        if let Ok(Some(status)) = child.try_wait() {
            tracing::error!(%status, "cli-proxy-api exited during startup");
            set_pgid(child_pgid, None);
            exited_during_startup = true;
            break;
        }
        tokio::select! {
            ready = probe_ready(probe_client, base_url, credential) => {
                if ready {
                    became_ready = true;
                    break;
                }
            }
            _ = shutdown_rx.changed() => {
                terminate(&mut child, pgid).await;
                set_pgid(child_pgid, None);
                return ChildAttempt::Shutdown;
            }
        }
        if wait_or_shutdown(shutdown_rx, tuning.readiness_poll).await {
            terminate(&mut child, pgid).await;
            set_pgid(child_pgid, None);
            return ChildAttempt::Shutdown;
        }
    }
    if exited_during_startup {
        return ChildAttempt::Ran { started_at };
    }
    if became_ready {
        tracing::info!("codex upstream ready");
        let _ = ready_tx.send(true);
    } else {
        // A live child that never becomes ready is a hang, not a crash:
        // terminate it and let the backoff loop start a fresh one, or GPT
        // routing would stay degraded forever.
        tracing::error!(
            log = %paths.log_file.display(),
            "cli-proxy-api did not become ready in time; restarting it (see its log)"
        );
        terminate(&mut child, pgid).await;
        set_pgid(child_pgid, None);
        return ChildAttempt::Ran { started_at };
    }

    // Wait for exit or shutdown.
    let attempt = tokio::select! {
        status = child.wait() => {
            let _ = ready_tx.send(false);
            match status {
                Ok(status) => tracing::error!(%status, "cli-proxy-api exited; restarting"),
                Err(error) => tracing::error!(%error, "failed to wait on cli-proxy-api"),
            }
            ChildAttempt::Ran { started_at }
        }
        _ = shutdown_rx.changed() => {
            let _ = ready_tx.send(false);
            terminate(&mut child, pgid).await;
            ChildAttempt::Shutdown
        }
    };
    set_pgid(child_pgid, None);
    attempt
}

fn set_pgid(slot: &SharedPgid, pgid: impl Into<Option<i32>>) {
    if let Ok(mut guard) = slot.lock() {
        *guard = pgid.into();
    }
}

/// True when shutdown was requested — or the `Supervisor` was dropped
/// (sender gone), which must also stop the loop or it would spin hot.
fn is_shutdown(shutdown_rx: &watch::Receiver<bool>) -> bool {
    shutdown_rx.has_changed().is_err() || *shutdown_rx.borrow()
}

/// Returns true when shutdown was requested during the wait.
async fn wait_or_shutdown(shutdown_rx: &mut watch::Receiver<bool>, wait: Duration) -> bool {
    tokio::select! {
        () = tokio::time::sleep(wait) => is_shutdown(shutdown_rx),
        result = shutdown_rx.changed() => result.is_err() || *shutdown_rx.borrow(),
    }
}

async fn spawn_child(
    binary: &PathBuf,
    paths: &ManagedPaths,
) -> anyhow::Result<tokio::process::Child> {
    let log = tokio::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&paths.log_file)
        .await
        .with_context(|| format!("failed to open {}", paths.log_file.display()))?;
    let mut log_for_stamp = log.try_clone().await?;
    let stamp = format!(
        "\n--- model-router spawning cli-proxy-api at {} ---\n",
        chrono::Utc::now().to_rfc3339()
    );
    let _ = log_for_stamp.write_all(stamp.as_bytes()).await;
    let log_std = log.into_std().await;
    let stderr_log = log_std.try_clone().context("failed to clone log handle")?;

    let mut command = tokio::process::Command::new(binary);
    command
        .arg("-config")
        .arg(&paths.upstream_config)
        .stdin(Stdio::null())
        .stdout(log_std)
        .stderr(stderr_log);
    #[cfg(unix)]
    {
        // New process group so shutdown can kill the child and anything it
        // spawns without touching the router's own group.
        command.process_group(0);
    }
    command.spawn().context("failed to spawn cli-proxy-api")
}

async fn terminate(child: &mut tokio::process::Child, pgid: Option<i32>) {
    #[cfg(unix)]
    if let Some(pgid) = pgid.filter(|pgid| *pgid > 0) {
        // SAFETY: signaling a process group we created.
        unsafe {
            libc::killpg(pgid, libc::SIGTERM);
        }
        if tokio::time::timeout(SHUTDOWN_GRACE, child.wait())
            .await
            .is_ok()
        {
            return;
        }
        tracing::warn!("cli-proxy-api ignored SIGTERM; killing");
        // SAFETY: as above.
        unsafe {
            libc::killpg(pgid, libc::SIGKILL);
        }
        let _ = child.wait().await;
        return;
    }
    let _ = child.kill().await;
}

/// Authenticated readiness probe: /v1/models with the injected credential
/// must return 200 JSON. A bare TCP accept is never treated as readiness.
/// Uses the same `GptUpstreamCredential` as the proxy request path so the
/// probe can never validate a different auth shape than real requests use.
async fn probe_ready(
    client: &reqwest::Client,
    base_url: &str,
    credential: &crate::headers::GptUpstreamCredential,
) -> bool {
    let Ok(response) = credential
        .apply(client.get(format!("{base_url}/v1/models")))
        .send()
        .await
    else {
        return false;
    };
    if !response.status().is_success() {
        return false;
    }
    let Ok(body) = response.bytes().await else {
        return false;
    };
    serde_json::from_slice::<serde_json::Value>(&body).is_ok_and(|value| value.is_object())
}

/// True when something is already listening on the loopback port.
async fn port_in_use(port: u16) -> bool {
    tokio::net::TcpStream::connect(("127.0.0.1", port))
        .await
        .is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaml_config_contains_hardening_flags() {
        let yaml = upstream_config_yaml(8317, std::path::Path::new("/tmp/auth"), "secret123");
        assert!(yaml.contains("host: \"127.0.0.1\""));
        assert!(yaml.contains("disable-claude-cloak-mode: true"));
        assert!(yaml.contains("disable-control-panel: true"));
        assert!(yaml.contains("usage-statistics-enabled: false"));
        assert!(yaml.contains("- \"secret123\""));
        assert!(yaml.contains("auth-dir: \"/tmp/auth\""));
    }

    #[tokio::test]
    async fn port_in_use_detects_listener() {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();
        assert!(port_in_use(port).await);
        drop(listener);
    }

    fn fast_tuning() -> Tuning {
        Tuning {
            readiness_timeout: Duration::from_millis(300),
            readiness_poll: Duration::from_millis(50),
            backoff_initial: Duration::from_millis(50),
            backoff_max: Duration::from_millis(100),
            backoff_reset_uptime: Duration::from_mins(1),
        }
    }

    fn dirs_with_fake_upstream(root: &std::path::Path, script_body: &str) -> Dirs {
        let dirs = Dirs {
            config_dir: root.join("config"),
            state_dir: root.join("state"),
            cache_dir: root.join("cache"),
        };
        let binary = dirs.upstream_binary(crate::acquire::UPSTREAM_VERSION);
        std::fs::create_dir_all(binary.parent().unwrap()).unwrap();
        std::fs::write(&binary, script_body).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&binary, std::fs::Permissions::from_mode(0o755)).unwrap();
        }
        dirs
    }

    fn free_port() -> u16 {
        std::net::TcpListener::bind("127.0.0.1:0")
            .unwrap()
            .local_addr()
            .unwrap()
            .port()
    }

    #[tokio::test]
    async fn live_but_unready_child_is_terminated_and_respawned() {
        let root = tempfile::tempdir().unwrap();
        let spawn_log = root.path().join("spawns");
        // A child that runs but never serves the port: readiness must time
        // out, the supervisor must kill it and spawn a fresh one.
        let script = format!(
            "#!/bin/sh\necho spawned >> {}\nexec sleep 60\n",
            spawn_log.display()
        );
        let dirs = dirs_with_fake_upstream(root.path(), &script);
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        let supervisor = Supervisor::start(&dirs, &upstream, fast_tuning()).unwrap();
        let handle = supervisor.handle();
        tokio::time::sleep(Duration::from_millis(1500)).await;
        assert!(!handle.is_ready());
        let spawns = std::fs::read_to_string(&spawn_log).unwrap_or_default();
        assert!(
            spawns.lines().count() >= 2,
            "expected the hung child to be restarted, saw {} spawn(s)",
            spawns.lines().count()
        );
        supervisor.shutdown().await;
    }

    #[tokio::test]
    async fn shutdown_never_leaves_a_live_child() {
        let root = tempfile::tempdir().unwrap();
        let pid_file = root.path().join("child-pid");
        // A child that ignores SIGTERM: shutdown must escalate to SIGKILL
        // and never return with the process alive.
        let script = format!(
            "#!/bin/sh\ntrap '' TERM\necho $$ > {}\nexec sleep 60\n",
            pid_file.display()
        );
        let dirs = dirs_with_fake_upstream(root.path(), &script);
        let upstream = UpstreamConfig {
            port: free_port(),
            ..UpstreamConfig::default()
        };
        let supervisor = Supervisor::start(&dirs, &upstream, fast_tuning()).unwrap();
        // Let the child spawn, then shut down mid-readiness.
        tokio::time::sleep(Duration::from_millis(200)).await;
        supervisor.shutdown().await;
        if let Ok(pid_text) = std::fs::read_to_string(&pid_file) {
            let pid: i32 = pid_text.trim().parse().unwrap();
            // SAFETY: signal 0 only checks liveness.
            let alive = unsafe { libc::kill(pid, 0) } == 0;
            assert!(!alive, "child {pid} survived shutdown");
        }
    }

    #[tokio::test]
    async fn occupied_port_prevents_any_spawn() {
        let root = tempfile::tempdir().unwrap();
        let spawn_log = root.path().join("spawns");
        let script = format!(
            "#!/bin/sh\necho spawned >> {}\nexec sleep 60\n",
            spawn_log.display()
        );
        let dirs = dirs_with_fake_upstream(root.path(), &script);
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let upstream = UpstreamConfig {
            port: listener.local_addr().unwrap().port(),
            ..UpstreamConfig::default()
        };
        let supervisor = Supervisor::start(&dirs, &upstream, fast_tuning()).unwrap();
        tokio::time::sleep(Duration::from_millis(600)).await;
        assert!(
            !spawn_log.exists(),
            "the supervisor must never spawn while a foreign listener holds the port"
        );
        assert!(!supervisor.handle().is_ready());
        supervisor.shutdown().await;
        drop(listener);
    }
}
