/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthorizedRouteImport } from './routes/authorized'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedIndexRouteImport } from './routes/authorized/index'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedPolicyRouteImport } from './routes/_authenticated/policy'
import { Route as AuthenticatedInstallRouteImport } from './routes/_authenticated/install'
import { Route as AuthenticatedConsentRouteImport } from './routes/_authenticated/consent'
import { Route as AuthorizedUsersIndexRouteImport } from './routes/authorized/users/index'
import { Route as AuthorizedSessionsIndexRouteImport } from './routes/authorized/sessions/index'
import { Route as AuthorizedUsersUserIdRouteImport } from './routes/authorized/users/$userId'
import { Route as AuthorizedSessionsSessionIdRouteImport } from './routes/authorized/sessions/$sessionId'
import { Route as ApiGithubInstalledRouteImport } from './routes/api/github/installed'
import { Route as AuthenticatedConsentProjectsRouteImport } from './routes/_authenticated/consent_.projects'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/authorized',
  path: '/authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedIndexRoute = AuthorizedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/auth/sign-out',
  path: '/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPolicyRoute = AuthenticatedPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstallRoute = AuthenticatedInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsentRoute = AuthenticatedConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthorizedUsersIndexRoute = AuthorizedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedSessionsIndexRoute = AuthorizedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedUsersUserIdRoute = AuthorizedUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedSessionsSessionIdRoute =
  AuthorizedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthorizedRoute,
  } as any)
const ApiGithubInstalledRoute = ApiGithubInstalledRouteImport.update({
  id: '/api/github/installed',
  path: '/api/github/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsentProjectsRoute =
  AuthenticatedConsentProjectsRouteImport.update({
    id: '/consent_/projects',
    path: '/consent/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorized': typeof AuthorizedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/install': typeof AuthenticatedInstallRoute
  '/policy': typeof AuthenticatedPolicyRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/authorized/': typeof AuthorizedIndexRoute
  '/consent/projects': typeof AuthenticatedConsentProjectsRoute
  '/api/github/installed': typeof ApiGithubInstalledRoute
  '/authorized/sessions/$sessionId': typeof AuthorizedSessionsSessionIdRoute
  '/authorized/users/$userId': typeof AuthorizedUsersUserIdRoute
  '/authorized/sessions': typeof AuthorizedSessionsIndexRoute
  '/authorized/users': typeof AuthorizedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/install': typeof AuthenticatedInstallRoute
  '/policy': typeof AuthenticatedPolicyRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/authorized': typeof AuthorizedIndexRoute
  '/consent/projects': typeof AuthenticatedConsentProjectsRoute
  '/api/github/installed': typeof ApiGithubInstalledRoute
  '/authorized/sessions/$sessionId': typeof AuthorizedSessionsSessionIdRoute
  '/authorized/users/$userId': typeof AuthorizedUsersUserIdRoute
  '/authorized/sessions': typeof AuthorizedSessionsIndexRoute
  '/authorized/users': typeof AuthorizedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/authorized': typeof AuthorizedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/consent': typeof AuthenticatedConsentRoute
  '/_authenticated/install': typeof AuthenticatedInstallRoute
  '/_authenticated/policy': typeof AuthenticatedPolicyRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/authorized/': typeof AuthorizedIndexRoute
  '/_authenticated/consent_/projects': typeof AuthenticatedConsentProjectsRoute
  '/api/github/installed': typeof ApiGithubInstalledRoute
  '/authorized/sessions/$sessionId': typeof AuthorizedSessionsSessionIdRoute
  '/authorized/users/$userId': typeof AuthorizedUsersUserIdRoute
  '/authorized/sessions/': typeof AuthorizedSessionsIndexRoute
  '/authorized/users/': typeof AuthorizedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorized'
    | '/callback'
    | '/consent'
    | '/install'
    | '/policy'
    | '/welcome'
    | '/auth/sign-out'
    | '/authorized/'
    | '/consent/projects'
    | '/api/github/installed'
    | '/authorized/sessions/$sessionId'
    | '/authorized/users/$userId'
    | '/authorized/sessions'
    | '/authorized/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/consent'
    | '/install'
    | '/policy'
    | '/welcome'
    | '/auth/sign-out'
    | '/authorized'
    | '/consent/projects'
    | '/api/github/installed'
    | '/authorized/sessions/$sessionId'
    | '/authorized/users/$userId'
    | '/authorized/sessions'
    | '/authorized/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/authorized'
    | '/callback'
    | '/_authenticated/consent'
    | '/_authenticated/install'
    | '/_authenticated/policy'
    | '/_authenticated/welcome'
    | '/auth/sign-out'
    | '/authorized/'
    | '/_authenticated/consent_/projects'
    | '/api/github/installed'
    | '/authorized/sessions/$sessionId'
    | '/authorized/users/$userId'
    | '/authorized/sessions/'
    | '/authorized/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  ApiGithubInstalledRoute: typeof ApiGithubInstalledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorized': {
      id: '/authorized'
      path: '/authorized'
      fullPath: '/authorized'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorized/': {
      id: '/authorized/'
      path: '/'
      fullPath: '/authorized/'
      preLoaderRoute: typeof AuthorizedIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policy': {
      id: '/_authenticated/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AuthenticatedPolicyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/install': {
      id: '/_authenticated/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof AuthenticatedInstallRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consent': {
      id: '/_authenticated/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthenticatedConsentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authorized/users/': {
      id: '/authorized/users/'
      path: '/users'
      fullPath: '/authorized/users'
      preLoaderRoute: typeof AuthorizedUsersIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/authorized/sessions/': {
      id: '/authorized/sessions/'
      path: '/sessions'
      fullPath: '/authorized/sessions'
      preLoaderRoute: typeof AuthorizedSessionsIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/authorized/users/$userId': {
      id: '/authorized/users/$userId'
      path: '/users/$userId'
      fullPath: '/authorized/users/$userId'
      preLoaderRoute: typeof AuthorizedUsersUserIdRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/authorized/sessions/$sessionId': {
      id: '/authorized/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/authorized/sessions/$sessionId'
      preLoaderRoute: typeof AuthorizedSessionsSessionIdRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/api/github/installed': {
      id: '/api/github/installed'
      path: '/api/github/installed'
      fullPath: '/api/github/installed'
      preLoaderRoute: typeof ApiGithubInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consent_/projects': {
      id: '/_authenticated/consent_/projects'
      path: '/consent/projects'
      fullPath: '/consent/projects'
      preLoaderRoute: typeof AuthenticatedConsentProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConsentRoute: typeof AuthenticatedConsentRoute
  AuthenticatedInstallRoute: typeof AuthenticatedInstallRoute
  AuthenticatedPolicyRoute: typeof AuthenticatedPolicyRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedConsentProjectsRoute: typeof AuthenticatedConsentProjectsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConsentRoute: AuthenticatedConsentRoute,
  AuthenticatedInstallRoute: AuthenticatedInstallRoute,
  AuthenticatedPolicyRoute: AuthenticatedPolicyRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedConsentProjectsRoute: AuthenticatedConsentProjectsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthorizedRouteChildren {
  AuthorizedIndexRoute: typeof AuthorizedIndexRoute
  AuthorizedSessionsSessionIdRoute: typeof AuthorizedSessionsSessionIdRoute
  AuthorizedUsersUserIdRoute: typeof AuthorizedUsersUserIdRoute
  AuthorizedSessionsIndexRoute: typeof AuthorizedSessionsIndexRoute
  AuthorizedUsersIndexRoute: typeof AuthorizedUsersIndexRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedIndexRoute: AuthorizedIndexRoute,
  AuthorizedSessionsSessionIdRoute: AuthorizedSessionsSessionIdRoute,
  AuthorizedUsersUserIdRoute: AuthorizedUsersUserIdRoute,
  AuthorizedSessionsIndexRoute: AuthorizedSessionsIndexRoute,
  AuthorizedUsersIndexRoute: AuthorizedUsersIndexRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthorizedRoute: AuthorizedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  ApiGithubInstalledRoute: ApiGithubInstalledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
