import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, spyOn, test } from 'bun:test';
import { localCore, localEnv, parseArgs } from '../commands/local';
import { toClaudeProjectDirName } from '../lib/config';
import { clipAround, clipFirstLine, clipStart, localTime } from '../lib/local-rows';
import { localHelp, localUsage } from '../lib/messages';
import { stdout } from '../lib/stdout';
import type { LocalEnv } from '../commands/local';

const A = 'aa000001-0000-4000-8000-000000000001'; // newest session: noise, tools, an agent
const B = 'bb000002-0000-4000-8000-000000000002'; // a rewind
const C = 'cc000003-0000-4000-8000-000000000003'; // empty: only a meta record
const D = 'dd000004-0000-4000-8000-000000000004'; // another project
const W = 'ee000005-0000-4000-8000-000000000005'; // another project: a Workflow with six agents
const AGENT = 'a1b2c3d4e5f6a7b8c';
const COMPACT = 'acompact-0123abcd'; // an auto-compaction agent of A
const ELSEWHERE = 'a9999999999999999'; // an agent of A stored under another project dir
const T = (minute: number) => `2026-09-20T10:${String(minute).padStart(2, '0')}:00.000Z`;

let k = 0;
const rec = (type: string, content: unknown, extra: Record<string, unknown> = {}) => ({
  type,
  uuid: `u-${++k}`,
  parentUuid: null,
  timestamp: T(k),
  gitBranch: 'main',
  isSidechain: false,
  message: type === 'assistant' ? { id: `m-${k}`, model: 'claude-x', content } : { content },
  ...extra,
});
const chain = (records: Array<Record<string, unknown>>) =>
  records.map((r, i) => ({ ...r, parentUuid: r.parentUuid ?? (i ? records[i - 1].uuid : null) }));
const J = (records: Array<object>) => records.map((r) => JSON.stringify(r)).join('\n') + '\n';

let root = '';
const project = () => join(root, '-p-proj');
const env = (): LocalEnv => ({
  root,
  project: (path) => Promise.resolve({ dirs: [project()], belongs: () => true, root: path }),
});
const write = async (path: string, content: string) => {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
};

beforeAll(async () => {
  root = await mkdtemp(join(tmpdir(), 'hive-local-'));
  k = 0;
  await write(
    join(project(), `${A}.jsonl`),
    J([
      ...chain([
        rec('user', 'Why does "the build" fail?', { origin: { kind: 'human' } }),
        rec('assistant', [
          { type: 'thinking', thinking: '' },
          { type: 'text', text: 'Running the tests.' },
        ]),
        rec('assistant', [{ type: 'tool_use', id: 'tu-bash', name: 'Bash', input: { command: 'bun test' } }]),
        rec('user', [
          { type: 'tool_result', tool_use_id: 'tu-bash', content: `3 fail\n${'x'.repeat(700)}`, is_error: true },
        ]),
        rec('assistant', [{ type: 'tool_use', id: 'tu-agent', name: 'Agent', input: { description: 'review' } }]),
        rec('user', [{ type: 'tool_result', tool_use_id: 'tu-agent', content: 'launched' }], {
          toolUseResult: { agentId: AGENT, status: 'async_launched' },
        }),
        rec('user', '<task-notification>\n<task-id>x</task-id>\n</task-notification>'),
        rec('user', 'Caveat: the messages below were generated by local commands', { isMeta: true }),
        rec('user', 'Another Claude session sent a message:\n<agent-message from="z">hi</agent-message>', {
          isMeta: true,
          origin: { kind: 'peer' },
        }),
        rec('system', undefined, { subtype: 'turn_duration', content: '' }),
        rec('system', undefined, { subtype: 'compact_boundary', content: 'Conversation compacted' }),
        rec('user', 'Summary of the work so far.', { isCompactSummary: true }),
        rec('assistant', [{ type: 'text', text: 'The needle is in "quotes".' }]),
      ]),
      { type: 'ai-title', aiTitle: 'Build failure', sessionId: A },
    ]),
  );
  await write(
    join(project(), A, 'subagents', `agent-${AGENT}.jsonl`),
    J(
      chain([
        rec('user', 'Review the needle fix.', { isSidechain: true }),
        rec('assistant', [{ type: 'text', text: 'Looks fine.' }], { isSidechain: true }),
      ]),
    ),
  );
  await write(join(project(), A, 'subagents', `agent-${AGENT}.meta.json`), JSON.stringify({ toolUseId: 'tu-agent' }));
  k = 0;
  const u1 = rec('user', 'Name the script.', { timestamp: '2026-09-19T09:00:00.000Z' });
  const a1 = rec('assistant', [{ type: 'text', text: 'sync-notes?' }], {
    parentUuid: u1.uuid,
    timestamp: '2026-09-19T09:00:05.000Z',
  });
  const u2 = rec('user', 'Shorter.', { parentUuid: a1.uuid, timestamp: '2026-09-19T09:00:10.000Z' });
  const a2 = rec('assistant', [{ type: 'text', text: 'sn?' }], {
    parentUuid: u2.uuid,
    timestamp: '2026-09-19T09:00:15.000Z',
  });
  const r = rec('user', 'Something about backups.', { parentUuid: a1.uuid, timestamp: '2026-09-19T09:00:20.000Z' });
  await write(join(project(), `${B}.jsonl`), J([u1, a1, u2, a2, r]));
  await write(join(project(), `${C}.jsonl`), J([rec('user', 'Caveat: nothing typed', { isMeta: true })]));
  await write(
    join(root, '-p-other', `${D}.jsonl`),
    J(chain([rec('user', 'Other project.', { cwd: '/elsewhere' }), rec('assistant', [{ type: 'text', text: 'ok' }])])),
  );
  await write(
    join(project(), A, 'subagents', `agent-${COMPACT}.jsonl`),
    J([
      rec('user', 'Compaction summary with the needle.', { isSidechain: true, timestamp: '2026-09-20T09:00:00.000Z' }),
    ]),
  );
  await write(
    join(root, '-p-other', A, 'subagents', `agent-${ELSEWHERE}.jsonl`),
    J([rec('user', 'Stored under another project dir.', { isSidechain: true })]),
  );
  const t = (s: number) => `2026-09-18T08:00:0${s}.000Z`;
  await write(
    join(root, '-p-other', `${W}.jsonl`),
    J(
      chain([
        rec('user', 'Run the workflow.', { timestamp: t(0) }),
        rec(
          'assistant',
          [
            {
              type: 'tool_use',
              id: 'tu-wf',
              name: 'Workflow',
              input: { script: 'fan out', items: Array.from({ length: 30 }, () => 'y'.repeat(100)) },
            },
          ],
          { timestamp: t(1) },
        ),
        rec('user', [{ type: 'tool_result', tool_use_id: 'tu-wf', content: 'Workflow started' }], {
          timestamp: t(2),
          toolUseResult: { runId: 'wf_run1' },
        }),
        rec('system', undefined, { subtype: 'agents_killed', timestamp: t(3) }),
        // A last record longer than the 64 KB tail chunk.
        rec('assistant', [{ type: 'text', text: 'z'.repeat(70_000) }], { timestamp: t(4), gitBranch: 'feature' }),
      ]),
    ),
  );
  for (let i = 1; i <= 6; i++)
    await write(
      join(root, '-p-other', W, 'subagents', 'workflows', 'wf_run1', `agent-b00000000000000${i}.jsonl`),
      J([rec('user', `Leaf ${i}.`, { isSidechain: true })]),
    );
  // Leaf 1 woken after the run ended: Claude Code continues it under the same id, outside the run.
  await write(
    join(root, '-p-other', W, 'subagents', 'agent-b000000000000001.jsonl'),
    J(
      chain([
        rec('user', 'Leaf 1, continued.', { isSidechain: true }),
        rec('assistant', [{ type: 'text', text: 'Done.' }], { isSidechain: true }),
      ]),
    ),
  );
});

afterAll(async () => {
  await rm(root, { recursive: true, force: true });
});

const out: Array<string> = [];
const err: Array<string> = [];
beforeEach(() => {
  out.length = 0;
  err.length = 0;
  spyOn(stdout, 'write').mockImplementation((s: string) => {
    // Each line is one write, its newline included (a pipe must never see a line without it).
    expect(s.endsWith('\n')).toBe(true);
    out.push(s.slice(0, -1));
  });
  spyOn(process.stderr, 'write').mockImplementation(((s: string) => {
    err.push(s.replace(/\n$/, ''));
    return true;
  }) as typeof process.stderr.write);
});
afterEach(() => {
  (stdout.write as unknown as { mockRestore: () => void }).mockRestore();
  (process.stderr.write as unknown as { mockRestore: () => void }).mockRestore();
});

const hl = (...argv: Array<string>) => localCore(env(), argv);
const rows = () => out.map((line) => JSON.parse(line) as Record<string, unknown>);

describe('help and errors', () => {
  test('the one help page, from every verb', async () => {
    for (const argv of [[], ['--help'], ['show', '--help'], ['grep', '-h']]) {
      out.length = 0;
      expect(await hl(...argv)).toBe(0);
      expect(out).toEqual([localHelp]);
    }
  });

  test('errors exit 2 and name the cause; a malformed call adds the usage lines', async () => {
    const cases: Array<[Array<string>, string]> = [
      [['bogus'], 'hive local: unknown command bogus'],
      [['show', A, '--bogus'], 'hive local: unknown flag --bogus for show'],
      [['sessions', '-n'], 'hive local: -n needs a value'],
      [['sessions', '-n', 'x'], 'hive local: bad value for -n: "x" (a whole number)'],
      [['sessions', 'extra'], 'hive local: sessions takes no SESSION ("extra"); use outline or show'],
      [['show'], 'hive local: show needs a SESSION'],
      [
        ['show', 'not-a-locator!'],
        'hive local: bad locator "not-a-locator!": use SESSION, SESSION:N, SESSION/agent-ID:N or SESSION/wf_RUN/agent-ID:N',
      ],
      [
        ['show', A, '5-3'],
        'hive local: bad range "5-3": use N, N-M or N- (entries start at 1) (after SESSION, show takes ranges of the transcript named last, or SESSION:N of any transcript)',
      ],
      [['show', `${A.slice(0, 8)}:99`], `hive local: entry 99 is out of range: ${A.slice(0, 8)} has entries 1-12`],
      [['show', 'ffffffff'], 'hive local: no session or agent matches "ffffffff"'],
      [
        ['outline', A, '3'],
        `hive local: outline takes one SESSION and no range ("${A} 3"); show SESSION RANGE prints entries`,
      ],
      [
        ['outline', `${A.slice(0, 8)}:4`],
        `hive local: outline takes one SESSION and no range ("${A.slice(0, 8)}:4"); show SESSION RANGE prints entries`,
      ],
      [
        ['outline', A.slice(0, 8), B.slice(0, 8)],
        `hive local: outline takes one SESSION and no range ("${A.slice(0, 8)} ${B.slice(0, 8)}"); show SESSION RANGE prints entries`,
      ],
      [['grep', '-c', '-l', 'x'], 'hive local: -c and -l cannot be used together'],
      [['sessions', '--project', '/dev/null'], 'hive local: --project /dev/null is not a directory'],
      [
        ['sessions', '--since', '2026-02-30'],
        'hive local: bad time "2026-02-30" for --since: use 2h, 7d, or a local date such as 2026-09-12',
      ],
      [['outline', 'agent-zz'], 'hive local: no agent matches "agent-zz"'],
      [['grep', '('], 'hive local: bad regex "(": missing )'],
      [
        ['grep', 'x', '--all-projects', '--project', '.'],
        'hive local: --project and --all-projects cannot be used together',
      ],
      [
        ['grep', 'x', A.slice(0, 8), '--project', '.'],
        'hive local: --project and --all-projects apply only to grep without SESSION arguments',
      ],
      [
        ['sessions', '--since', 'yesterday'],
        'hive local: bad time "yesterday" for --since: use 2h, 7d, or a local date such as 2026-09-12',
      ],
    ];
    for (const [argv, message] of cases) {
      err.length = 0;
      expect([argv, await hl(...argv)]).toEqual([argv, 2]);
      expect(err[0]).toBe(message);
    }
    err.length = 0;
    await hl('show', A, '--bogus');
    // Usage lines only: the rest of the help page, even a line starting "hive local", stays out.
    expect(err[1]).toBe(`usage:\n${localUsage}\nhive local --help for the whole page`);
    expect(err[1].split('\n').filter((l) => l.startsWith('  hive local'))).toHaveLength(4);
  });

  test('flag clusters, --flag=value, and -- before a leading-dash pattern', () => {
    const p = parseArgs('grep', ['-ic', '-m5', '--clip=0', '--', '-x', A]);
    expect([...p.flags]).toEqual([
      ['-i', true],
      ['-c', true],
      ['-m', '5'],
      ['--clip', '0'],
    ]);
    expect(p.positional).toEqual(['-x', A]);
  });
});

describe('clipping and time', () => {
  test('cuts at code points and marks what was cut', () => {
    expect(clipStart('abcdef', 3)).toBe('abc [+3 chars]');
    expect(clipStart('😀😀😀', 2)).toBe('😀😀 [+1 chars]');
    expect(clipFirstLine('  first line\nsecond', 150)).toBe('first line [+7 chars]');
    expect(clipAround('0123456789', 5, 1, 4)).toBe('[+4 chars] 4567 [+2 chars]');
    expect(localTime('2026-09-20T10:01:00.000Z')).toMatch(/^2026-09-2\dT\d\d:\d\d:00[+-]\d\d:\d\d$/);
  });
});

describe('sessions', () => {
  test('latest activity first; an empty session is left out; titles and first human messages', async () => {
    expect(await hl('sessions')).toBe(0);
    expect(rows()).toEqual([
      {
        loc: A.slice(0, 8),
        start: localTime(T(1)),
        end: localTime(T(13)),
        branch: 'main',
        title: 'Build failure',
        first: 'Why does "the build" fail?',
      },
      {
        loc: B.slice(0, 8),
        start: localTime('2026-09-19T09:00:00.000Z'),
        end: localTime('2026-09-19T09:00:20.000Z'),
        branch: 'main',
        first: 'Name the script.',
      },
    ]);
    expect(err).toEqual(['2 sessions']);
    out.length = 0;
    err.length = 0;
    await hl('sessions', '-n', '1', '--until', '2026-09-19');
    expect(rows().map((r) => r.loc)).toEqual([B.slice(0, 8)]);
    expect(err).toEqual(['1 session active in the --since/--until window']);
    // With both bounds, a session whose span covers the window but has no entry inside it is left out.
    out.length = 0;
    await hl('sessions', '--since', '2026-09-19T09:00:06Z', '--until', '2026-09-19T09:00:09Z');
    expect(rows()).toEqual([]);
    out.length = 0;
    await hl('sessions', '--since', '2026-09-19T09:00:04Z', '--until', '2026-09-19T09:00:06Z');
    expect(rows().map((r) => r.loc)).toEqual([B.slice(0, 8)]);
    out.length = 0;
    err.length = 0;
    await hl('sessions', '--all-projects', '-n', '1');
    expect(rows()[0]).toMatchObject({ loc: A.slice(0, 8), project: '-p-proj' });
    expect(err).toEqual(['1 of 4 sessions in all projects; -n N for more']);
    // The branch comes from the parse that found the last entry, here past the 64 KB tail chunk.
    out.length = 0;
    await hl('sessions', '--all-projects', '--until', '2026-09-18');
    expect(rows()).toEqual([
      {
        loc: W.slice(0, 8),
        project: '/elsewhere', // no cwd of its own: another file in its project dir has one
        start: localTime('2026-09-18T08:00:00.000Z'),
        end: localTime('2026-09-18T08:00:04.000Z'),
        branch: 'feature',
        first: 'Run the workflow.',
      },
    ]);
    out.length = 0;
    await hl('sessions', '--all-projects', '--since', '2026-09-20T10:14:00Z');
    expect(rows()).toEqual([]);
  });
});

describe('show and outline', () => {
  test('show: every visible entry, fields clipped, noise counted on stderr', async () => {
    expect(await hl('show', A.slice(0, 8))).toBe(0);
    const r = rows();
    expect(r.map((x) => [x.loc, x.kind])).toEqual([
      [`${A.slice(0, 8)}:1`, 'user'],
      [`${A.slice(0, 8)}:3`, 'assistant'],
      [`${A.slice(0, 8)}:4`, 'tool'],
      [`${A.slice(0, 8)}:5`, 'tool'],
      [`${A.slice(0, 8)}:8`, 'user'],
      [`${A.slice(0, 8)}:10`, 'system'],
      [`${A.slice(0, 8)}:12`, 'assistant'],
    ]);
    expect(r[2]).toEqual({
      loc: `${A.slice(0, 8)}:4`,
      time: localTime(T(3)),
      kind: 'tool',
      tool: 'Bash',
      input: { command: 'bun test' },
      result: `3 fail\n${'x'.repeat(700)}`,
      error: true,
    });
    expect(r[3]).toMatchObject({ tool: 'Agent', agents: [`${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}`] });
    expect(r[4]).toMatchObject({ origin: 'peer' });
    expect(err).toEqual([
      `${A.slice(0, 8)}: entries 1-12; printed 7; 5 hidden by noise rules (empty-thinking 1, task-notification 1, meta 1, system-bookkeeping 1, compact-summary 1); --all-entries shows them`,
    ]);
  });

  test('show: ranges, SESSION:N, --all-entries marks hidden entries, --clip 0', async () => {
    await hl('show', `${A.slice(0, 8)}:2`, '11-', '1', '--all-entries', '--clip', '0');
    expect(err).toEqual([`${A.slice(0, 8)}: entries 1-12; printed 4`]);
    // In the order given.
    expect(rows().map((x) => [x.loc, x.hidden])).toEqual([
      [`${A.slice(0, 8)}:2`, 'empty-thinking'],
      [`${A.slice(0, 8)}:11`, 'compact-summary'],
      [`${A.slice(0, 8)}:12`, undefined],
      [`${A.slice(0, 8)}:1`, undefined],
    ]);
  });

  test('show: a SESSION without a range is the whole transcript only when no bare RANGE follows', async () => {
    const a = A.slice(0, 8);
    const agent = `${a}/agent-${AGENT.slice(0, 8)}`;
    expect(await hl('show', a, '4-5', '1')).toBe(0);
    expect(rows().map((x) => x.loc)).toEqual([`${a}:4`, `${a}:5`, `${a}:1`]);
    expect(err).toEqual([`${a}: entries 1-12; printed 3`]);
    out.length = 0;
    expect(await hl('show', a, `${agent}:1`)).toBe(0);
    expect(rows().map((x) => x.loc)).toEqual([1, 3, 4, 5, 8, 10, 12].map((n) => `${a}:${n}`).concat(`${agent}:1`));
  });

  test('show: SESSION:N arguments of different transcripts print in the order given', async () => {
    const agent = `${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}`;
    expect(await hl('show', `${A.slice(0, 8)}:12`, `${agent}:1`, `${A.slice(0, 8)}:1`, '3')).toBe(0);
    expect(rows().map((x) => x.loc)).toEqual([
      `${A.slice(0, 8)}:12`,
      `${agent}:1`,
      `${A.slice(0, 8)}:1`,
      `${A.slice(0, 8)}:3`,
    ]);
    expect(err).toEqual([`${A.slice(0, 8)}: entries 1-12; printed 3`, `${agent}: entries 1-2; printed 1`]);
  });

  test('show: rewound entries are marked; an agent transcript by its printed locator', async () => {
    await hl('show', B.slice(0, 8));
    expect(rows().map((x) => [x.text, x.rewound])).toEqual([
      ['Name the script.', undefined],
      ['sync-notes?', undefined],
      ['Shorter.', true],
      ['sn?', true],
      ['Something about backups.', undefined],
    ]);
    out.length = 0;
    await hl('show', `${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}:1`);
    expect(rows()).toEqual([
      {
        loc: `${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}:1`,
        time: localTime(T(14)),
        kind: 'user',
        text: 'Review the needle fix.',
      },
    ]);
  });

  test('outline: the human messages, compactions and agent calls, first lines only', async () => {
    await hl('outline', A.slice(0, 8));
    expect(rows().map((x) => x.loc)).toEqual([`${A.slice(0, 8)}:1`, `${A.slice(0, 8)}:5`, `${A.slice(0, 8)}:10`]);
    // A call that started an agent: no launch notice.
    expect(rows()[1]).toEqual({
      loc: `${A.slice(0, 8)}:5`,
      time: localTime(T(5)),
      kind: 'tool',
      tool: 'Agent',
      input: { description: 'review' },
      agents: [`${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}`],
    });
    expect(err).toEqual([
      `${A.slice(0, 8)}: entries 1-12; printed 3; 2 hidden by noise rules (meta 1, compact-summary 1); --all-entries shows them`,
    ]);
    out.length = 0;
    await hl('outline', A.slice(0, 8), '--all-entries');
    expect(rows().map((x) => [x.loc, x.hidden])).toEqual([
      [`${A.slice(0, 8)}:1`, undefined],
      [`${A.slice(0, 8)}:5`, undefined],
      [`${A.slice(0, 8)}:7`, 'meta'],
      [`${A.slice(0, 8)}:10`, undefined],
      [`${A.slice(0, 8)}:11`, 'compact-summary'],
    ]);
  });
});

describe('long lists', () => {
  test('outline prints 5 agents and counts the rest; show prints them all and bounds a large input', async () => {
    await hl('outline', W.slice(0, 8));
    const call = rows()[1];
    expect(call).toMatchObject({ loc: `${W.slice(0, 8)}:2`, tool: 'Workflow' });
    expect(call.result).toBeUndefined();
    expect(call.agents).toHaveLength(6);
    expect((call.agents as Array<string>).at(-1)).toBe('[+1 items]');
    out.length = 0;
    await hl('show', `${W.slice(0, 8)}:2`, '--clip', '100');
    const row = rows()[0] as { agents: Array<string>; result: string; input: { script: string; items: Array<string> } };
    expect(row.agents).toHaveLength(6);
    expect(row.result).toBe('Workflow started');
    expect(row.input.script).toBe('fan out');
    expect(row.input.items).toEqual(['y'.repeat(100), 'y'.repeat(100), 'y'.repeat(100), '[+27 items]']);
    expect(out[0].length).toBeLessThan(4 * 100 + 400);
  });

  test('a system entry with no text prints without the key', async () => {
    await hl('show', `${W.slice(0, 8)}:3`);
    expect(rows()).toEqual([
      {
        loc: `${W.slice(0, 8)}:3`,
        time: localTime('2026-09-18T08:00:03.000Z'),
        kind: 'system',
        subtype: 'agents_killed',
      },
    ]);
  });
});

describe('an agent id with a file in a Workflow run and one outside it', () => {
  test('grep prints a distinct loc for each, and show resolves each loc to its own file', async () => {
    const w = W.slice(0, 8);
    expect(await hl('grep', '-c', 'Leaf 1', w, '--agents')).toBe(0);
    expect(rows()).toEqual([
      { loc: `${w}/agent-b000000000000001`, count: 1 },
      { loc: `${w}/wf_run1/agent-b000000000000001`, count: 1 },
    ]);
    const outside = `${w}/agent-b000000000000001`;
    const inRun = `${w}/wf_run1/agent-b000000000000001`;
    // Each file's entries keep their own numbers; stderr links the two parts of the one agent.
    for (const [loc, text, link] of [
      [
        outside,
        'Leaf 1, continued.',
        `${outside}: continues ${inRun}:1, the same agent's transcript in its Workflow run`,
      ],
      [inRun, 'Leaf 1.', `${inRun}: the same agent continued after its Workflow run in ${outside}`],
    ]) {
      out.length = 0;
      err.length = 0;
      expect(await hl('show', `${loc}:1`)).toBe(0);
      expect(rows().map((x) => [x.loc, x.text])).toEqual([[`${loc}:1`, text]]);
      expect(err.slice(1)).toEqual([link]);
    }
    // Bare ranges after a run-qualified locator are ranges of that transcript.
    out.length = 0;
    expect(await hl('show', outside, '2', '1')).toBe(0);
    expect(rows().map((x) => x.loc)).toEqual([`${outside}:2`, `${outside}:1`]);
    out.length = 0;
    expect(await hl('show', inRun, '1', '1')).toBe(0);
    expect(rows().map((x) => [x.loc, x.text])).toEqual([[`${inRun}:1`, 'Leaf 1.']]);
  });
});

describe('grep', () => {
  test('decoded text, sessions then their agents, snippets marked on both sides', async () => {
    expect(await hl('grep', 'needle')).toBe(0);
    expect(rows().map((x) => x.loc)).toEqual([`${A.slice(0, 8)}:12`]);
    expect(err).toEqual([`1 matching entry in 1 transcript; searched 3 sessions of ${process.cwd()} and its worktrees`]);
    out.length = 0;
    err.length = 0;
    expect(await hl('grep', 'Review the needle')).toBe(1);
    expect(err[0]).toEndWith('; --agents also searches their agent transcripts');
    out.length = 0;
    err.length = 0;
    expect(await hl('grep', 'needle', '--agents')).toBe(0);
    expect(rows().map((x) => [x.loc, x.text])).toEqual([
      [`${A.slice(0, 8)}:12`, 'The needle is in "quotes".'],
      [`${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}:1`, 'Review the needle fix.'],
    ]);
    // The compaction agent's copy of the needle is not searched unless A is named.
    expect(err).toEqual([
      `2 matching entries in 2 transcripts; searched 3 sessions and 2 agent transcripts of ${process.cwd()} and its worktrees`,
    ]);
    out.length = 0;
    await hl('grep', 'needle', A.slice(0, 8), '-l', '--agents');
    expect(rows().map((x) => x.loc)).toEqual([
      A.slice(0, 8),
      `${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}`,
      `${A.slice(0, 8)}/agent-acompact`,
    ]);
    // An agent stored under a project dir outside the scope is still its session's.
    out.length = 0;
    await hl('grep', 'another project dir', '--agents');
    expect(rows().map((x) => x.loc)).toEqual([`${A.slice(0, 8)}/agent-${ELSEWHERE.slice(0, 8)}:1`]);
    out.length = 0;
    await hl('grep', '"the build"');
    expect(rows().map((x) => x.loc)).toEqual([`${A.slice(0, 8)}:1`]);
    out.length = 0;
    await hl('grep', 'x{10}', '--clip', '20');
    // A tool hit shows the other side's first line.
    expect(rows()).toEqual([
      {
        loc: `${A.slice(0, 8)}:4`,
        time: localTime(T(3)),
        kind: 'tool',
        tool: 'Bash',
        input: { command: 'bun test' },
        result: '[+2 chars] fail\nxxxxxxxxxxxxxxx [+685 chars]',
        error: true,
      },
    ]);
    out.length = 0;
    await hl('grep', 'bun test');
    expect(rows()).toEqual([
      {
        loc: `${A.slice(0, 8)}:4`,
        time: localTime(T(3)),
        kind: 'tool',
        tool: 'Bash',
        input: { command: 'bun test' },
        result: '3 fail [+701 chars]',
        error: true,
      },
    ]);
  });

  test('--since keeps an agent that outlived its session', async () => {
    // The agent's entry (10:14) is after its session's last entry (10:13).
    for (const argv of [
      ['grep', 'needle', '--agents', '--since', '2026-09-20T10:14:00Z'],
      ['grep', 'needle', A.slice(0, 8), '--agents', '--since', '2026-09-20T10:14:00Z'],
    ]) {
      out.length = 0;
      expect([argv, await hl(...argv)]).toEqual([argv, 0]);
      expect(rows().map((x) => x.loc)).toEqual([`${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}:1`]);
    }
  });

  test('-c, -l, -m, -i, -F, --agents, SESSION arguments, and no match', async () => {
    await hl('grep', 'NEEDLE', '-ic', '--agents');
    expect(rows()).toEqual([
      { loc: A.slice(0, 8), count: 1 },
      { loc: `${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}`, count: 1 },
    ]);
    out.length = 0;
    await hl('grep', 'needle', '-l');
    expect(rows()).toEqual([{ loc: A.slice(0, 8) }]);
    out.length = 0;
    await hl('grep', '.', '-m', '1', B.slice(0, 8));
    expect(rows().map((x) => x.loc)).toEqual([`${B.slice(0, 8)}:1`]);
    out.length = 0;
    await hl('grep', '(quotes)', '-F');
    expect(out).toEqual([]);
    err.length = 0;
    expect(await hl('grep', 'task-id', '--agents')).toBe(1);
    expect(err[0]).toStartWith('no match in 3 sessions and 2 agent transcripts');
    expect(err[0]).toEndWith('; 1 more in hidden entries (--all-entries includes them)');
    out.length = 0;
    expect(await hl('grep', 'task-id', '--all-entries')).toBe(0);
    expect(rows()[0]).toMatchObject({ loc: `${A.slice(0, 8)}:6`, hidden: 'task-notification' });
  });
});

describe('found by trying every feature', () => {
  test('grep searches a transcript named twice (or as SESSION and SESSION:N) once', async () => {
    await hl('grep', '-c', '.', B.slice(0, 8), B.slice(0, 8), `${B.slice(0, 8)}:2`);
    expect(rows()).toEqual([{ loc: B.slice(0, 8), count: 5 }]);
    expect(err.at(-1)).toBe('5 matching entries in 1 transcript; searched 1 session');
    out.length = 0;
    await hl('grep', '.', `${B.slice(0, 8)}:2`, `${B.slice(0, 8)}:1-2`);
    expect(rows().map((x) => x.loc)).toEqual([`${B.slice(0, 8)}:1`, `${B.slice(0, 8)}:2`]);
  });

  test('grep of an agent alone counts agent transcripts, not "0 sessions"', async () => {
    await hl('grep', '-c', 'needle', `${A.slice(0, 8)}/agent-${AGENT.slice(0, 8)}`);
    expect(err.at(-1)).toBe('1 matching entry in 1 transcript; searched 1 agent transcript');
  });

  test('show checks every locator and range before printing anything', async () => {
    expect(await hl('show', `${A.slice(0, 8)}:1`, `${B.slice(0, 8)}:99`)).toBe(2);
    expect(out).toEqual([]);
    expect(await hl('show', `${A.slice(0, 8)}:1`, 'zzzzzzzz:1')).toBe(2);
    expect(out).toEqual([]);
  });

  test('a bare RANGE is of the transcript named last', async () => {
    await hl('show', `${A.slice(0, 8)}:1`, `${B.slice(0, 8)}:2`, '3');
    expect(rows().map((x) => x.loc)).toEqual([`${A.slice(0, 8)}:1`, `${B.slice(0, 8)}:2`, `${B.slice(0, 8)}:3`]);
  });

  test("outline of an agent's transcript lists its session's later messages to it", async () => {
    const S = 'ab000006-0000-4000-8000-000000000006';
    const X = 'a7777777777777777';
    await write(
      join(project(), S, 'subagents', `agent-${X}.jsonl`),
      J(
        chain([
          rec('user', 'Plan the stream.', { isSidechain: true }),
          rec('assistant', [{ type: 'text', text: 'Planning.' }], { isSidechain: true }),
          rec('user', 'A constraint from the owner.', {
            isSidechain: true,
            isMeta: true,
            origin: { kind: 'coordinator' },
          }),
          rec('user', 'Another agent says hi.', { isSidechain: true, isMeta: true, origin: { kind: 'peer' } }),
        ]),
      ),
    );
    await write(join(project(), `${S}.jsonl`), J([rec('user', 'Start.')]));
    await hl('outline', `${S.slice(0, 8)}/agent-${X.slice(0, 8)}`);
    expect(rows().map((x) => [x.loc, x.origin])).toEqual([
      [`${S.slice(0, 8)}/agent-${X.slice(0, 8)}:1`, undefined],
      [`${S.slice(0, 8)}/agent-${X.slice(0, 8)}:3`, 'coordinator'],
    ]);
    await rm(join(project(), S), { recursive: true });
    await rm(join(project(), `${S}.jsonl`));
  });

  test("Claude Code's orphaned title file is not a session", async () => {
    const orphan = join(project(), `${B}.orphaned-1783632973952-81c7d6d0.jsonl`);
    await write(orphan, J([{ type: 'ai-title', aiTitle: 'Stale', sessionId: B }]));
    expect(await hl('show', B.slice(0, 8), '1')).toBe(0);
    expect(rows().map((x) => x.loc)).toEqual([`${B.slice(0, 8)}:1`]);
    await rm(orphan);
  });

  test('a forked session starts at its own first entry, not the context it copied', async () => {
    const S = 'ad000008-0000-4000-8000-000000000008';
    await write(
      join(project(), `${S}.jsonl`),
      J([
        { type: 'queue-operation', operation: 'enqueue', timestamp: '2026-09-24T11:45:46.000Z', sessionId: S },
        ...chain([
          rec('user', 'Copied from the parent.', { timestamp: '2026-09-16T23:50:00.000Z' }),
          rec('assistant', [{ type: 'text', text: 'Copied reply.' }], { timestamp: '2026-09-16T23:51:00.000Z' }),
          rec('user', 'The fork speaks.', { timestamp: '2026-09-24T11:45:47.000Z' }),
        ]),
      ]),
    );
    await hl('sessions', '-n', '100');
    expect(rows().find((x) => x.loc === S.slice(0, 8))).toMatchObject({
      start: localTime('2026-09-24T11:45:47.000Z'),
    });
    out.length = 0;
    await hl('sessions', '-n', '100', '--since', '2026-09-16', '--until', '2026-09-17');
    expect(rows().map((x) => x.loc)).not.toContain(S.slice(0, 8));
    await rm(join(project(), `${S}.jsonl`));
  });

  test('piped output survives a slow reader: every line whole', async () => {
    const base = await realpath(await mkdtemp(join(tmpdir(), 'hive-pipe-')));
    const S = 'af00000a-0000-4000-8000-00000000000a';
    const saved = k; // T(k) must stay a valid minute for later fixtures
    const lines = Array.from({ length: 300 }, (_, i) => rec('user', `${i} ${'p'.repeat(2000)}`, { timestamp: T(1) }));
    k = saved;
    await write(join(base, 'projects', '-p', `${S}.jsonl`), J(chain(lines)));
    // The compiled binary, as shipped: console.log lost output there that `bun cli.ts` kept.
    const bin = join(base, 'hive');
    const build = Bun.spawnSync(['bun', 'build', '--compile', join(import.meta.dir, '..', 'cli.ts'), '--outfile', bin]);
    expect(build.exitCode).toBe(0);
    // A shell pipe to a reader that waits, so the pipe fills (Bun.spawn's own pipe reads eagerly).
    const child = Bun.spawnSync(['sh', '-c', '"$0" local show "$1" --clip 0 | (sleep 1; cat)', bin, S.slice(0, 8)], {
      env: { ...process.env, CLAUDE_CONFIG_DIR: base },
      stderr: 'ignore',
    });
    expect(child.exitCode).toBe(0);
    const text = child.stdout.toString();
    const printed = text.split('\n').filter(Boolean);
    expect(printed).toHaveLength(300);
    for (const line of printed) expect(() => JSON.parse(line)).not.toThrow();
    await rm(base, { recursive: true, force: true });
  });

  test('a session that began with a bare slash command lists it as first', async () => {
    const S = 'ac000007-0000-4000-8000-000000000007';
    await write(
      join(project(), `${S}.jsonl`),
      J(
        chain([
          rec(
            'user',
            '<command-name>/review</command-name>\n<command-message>review</command-message>\n<command-args></command-args>',
          ),
          rec('assistant', [{ type: 'text', text: 'Reviewing.' }]),
        ]),
      ),
    );
    await hl('sessions', '-n', '100');
    expect(rows().find((x) => x.loc === S.slice(0, 8))).toMatchObject({ first: '/review' });
    await rm(join(project(), `${S}.jsonl`));
  });
});

describe('CLAUDE_CONFIG_DIR and project scope', () => {
  const session = (cwd: string, text: string) =>
    J([{ type: 'user', uuid: `u-${text}`, timestamp: T(1), cwd, message: { content: text } }]);
  const withRoot = async (base: string, run: () => Promise<void>) => {
    const saved = process.env.CLAUDE_CONFIG_DIR;
    process.env.CLAUDE_CONFIG_DIR = join(base, 'new');
    try {
      await run();
    } finally {
      if (saved === undefined) delete process.env.CLAUDE_CONFIG_DIR;
      else process.env.CLAUDE_CONFIG_DIR = saved;
      await rm(base, { recursive: true, force: true });
    }
  };

  test("registries (current and legacy) keep only this root's dirs; listed sessions resolve, agents found", async () => {
    const base = await realpath(await mkdtemp(join(tmpdir(), 'hive-config-')));
    const proj = join(base, 'proj');
    await mkdir(proj, { recursive: true });
    execFileSync('git', ['init', '-q'], { cwd: proj, stdio: 'ignore' });
    const name = toClaudeProjectDirName(proj);
    const gone = `${name}-gone-worktree`; // a deleted worktree's dir, registered only by the plugin's old name
    const OLD = 'f0000001-0000-4000-8000-000000000001';
    const NEW = 'f0000002-0000-4000-8000-000000000002';
    const GONE = 'f0000003-0000-4000-8000-000000000003';
    const NEW_AGENT = 'a5555555555555555';
    await write(join(base, 'old', 'projects', name, `${OLD}.jsonl`), session(proj, 'Old root.'));
    await write(join(base, 'new', 'projects', name, `${NEW}.jsonl`), session(proj, 'New root.'));
    await write(join(base, 'new', 'projects', gone, `${GONE}.jsonl`), session(join(base, 'gone'), 'Gone worktree.'));
    await write(
      join(base, 'new', 'projects', name, NEW, 'subagents', `agent-${NEW_AGENT}.jsonl`),
      J([rec('user', 'Agent under the new root.', { isSidechain: true })]),
    );
    await write(
      join(proj, '.claude', 'hive', 'transcripts-dirs'),
      `${join(base, 'old', 'projects', name)}\n${join(base, 'new', 'projects', name)}\n`,
    );
    await write(join(proj, '.claude', 'hive-mind', 'transcripts-dirs'), `${join(base, 'new', 'projects', gone)}\n`);
    await withRoot(base, async () => {
      const real = localEnv();
      expect(await localCore(real, ['sessions', '--project', proj])).toBe(0);
      const locs = rows().map((x) => x.loc as string);
      expect(locs.sort()).toEqual([NEW.slice(0, 8), GONE.slice(0, 8)].sort());
      for (const loc of locs) {
        out.length = 0;
        expect(await localCore(real, ['show', loc])).toBe(0);
      }
      out.length = 0;
      expect(await localCore(real, ['grep', '-l', 'under the new root', '--agents', '--project', proj])).toBe(0);
      expect(rows()).toEqual([{ loc: `${NEW.slice(0, 8)}/agent-${NEW_AGENT.slice(0, 8)}` }]);
    });
  });

  test('--project on a folder outside git is that folder only, whatever its registry says', async () => {
    const base = await realpath(await mkdtemp(join(tmpdir(), 'hive-folder-')));
    const folder = join(base, 'notes');
    const sub = join(folder, 'sub');
    const HERE = 'f0000004-0000-4000-8000-000000000004';
    const BELOW = 'f0000005-0000-4000-8000-000000000005';
    await write(join(base, 'new', 'projects', toClaudeProjectDirName(folder), `${HERE}.jsonl`), session(folder, 'Here.'));
    await write(join(base, 'new', 'projects', toClaudeProjectDirName(sub), `${BELOW}.jsonl`), session(sub, 'Below.'));
    await write(
      join(folder, '.claude', 'hive', 'transcripts-dirs'),
      `${join(base, 'new', 'projects', toClaudeProjectDirName(sub))}\n`,
    );
    await withRoot(base, async () => {
      expect(await localCore(localEnv(), ['sessions', '--project', folder])).toBe(0);
      expect(rows().map((x) => x.loc)).toEqual([HERE.slice(0, 8)]);
      out.length = 0;
      err.length = 0;
      expect(await localCore(localEnv(), ['grep', '-c', '.', '--project', folder])).toBe(0);
      expect(err.at(-1)).toBe(
        `1 matching entry in 1 transcript; searched 1 session of ${folder} (not a git repository: that folder only)`,
      );
    });
  });
});
